/**
 * Key Generation Entropy Auditor
 * Takes a real batch of wallet addresses generated by the developer's system
 * and runs statistical tests to detect weak randomness — the same analysis
 * a researcher would run when hunting for Profanity-style vulnerabilities.
 *
 * All analysis is purely on the address data provided. No private keys are
 * accepted or processed.
 */

export interface EntropyFinding {
  id: string;
  severity: "critical" | "high" | "medium" | "low" | "pass";
  title: string;
  detail: string;
  attackVector: string;
  remediation: string;
  evidence?: string;
}

export interface KeyEntropyResult {
  addressCount: number;
  validAddresses: string[];
  invalidAddresses: string[];
  findings: EntropyFinding[];
  stats: {
    byteFrequency: number[];         // 0-255: avg frequency of each byte value across all addresses
    chiSquaredStatistic: number;     // Higher = more deviation from uniform
    chiSquaredPValue: string;        // "p<0.001", "p<0.01", "p<0.05", "p>0.05"
    bitBias: number;                 // 0=perfectly balanced, higher=biased
    avgHammingDistance: number;      // Average Hamming distance between consecutive pairs
    minHammingDistance: number;      // Minimum Hamming distance found (low = nearly identical keys)
    leadingZeroAddresses: number;    // Addresses with leading zero bytes (gas optimization exploit)
    sequentialAddresses: number;     // Addresses that differ by only 1-2 bytes from another
    duplicateAddresses: number;
    nullByteHeavyAddresses: number;  // Addresses with >4 null bytes (extremely suspicious)
    profanityPattern: boolean;       // Matches Profanity GPU wallet gen vulnerability pattern
    knownWeakPatterns: string[];
  };
  riskScore: number;
}

function parseAddresses(input: string[]): { valid: string[]; invalid: string[] } {
  const valid: string[] = [];
  const invalid: string[] = [];
  const seen = new Set<string>();
  for (const addr of input) {
    const trimmed = addr.trim().toLowerCase();
    if (/^(?:0x)?[0-9a-f]{40}$/.test(trimmed)) {
      const normalized = trimmed.startsWith("0x") ? trimmed : "0x" + trimmed;
      valid.push(normalized);
      seen.add(normalized);
    } else if (trimmed.length > 0) {
      invalid.push(addr.trim());
    }
  }
  return { valid, invalid };
}

function addressToBytes(addr: string): number[] {
  const hex = addr.replace("0x", "");
  const bytes: number[] = [];
  for (let i = 0; i < hex.length; i += 2) {
    bytes.push(parseInt(hex.slice(i, i + 2), 16));
  }
  return bytes;
}

function hammingDistance(a: string, b: string): number {
  const ba = addressToBytes(a);
  const bb = addressToBytes(b);
  let distance = 0;
  for (let i = 0; i < ba.length; i++) {
    let xor = (ba[i] ?? 0) ^ (bb[i] ?? 0);
    while (xor) { distance += xor & 1; xor >>= 1; }
  }
  return distance;
}

function chiSquaredTest(observed: number[], totalSamples: number): { stat: number; pValue: string } {
  const k = observed.length;
  const expected = totalSamples / k;
  let stat = 0;
  for (const o of observed) {
    stat += Math.pow(o - expected, 2) / expected;
  }
  // Critical values for chi-squared with 255 degrees of freedom
  const stat_p001 = 310.46;
  const stat_p01  = 291.88;
  const stat_p05  = 274.59;
  let pValue: string;
  if (stat > stat_p001)     pValue = "p<0.001";
  else if (stat > stat_p01)  pValue = "p<0.01";
  else if (stat > stat_p05)  pValue = "p<0.05";
  else                       pValue = "p>0.05";
  return { stat, pValue };
}

function computeBitBias(addresses: string[]): number {
  let totalBits = 0;
  let setBits = 0;
  for (const addr of addresses) {
    const bytes = addressToBytes(addr);
    for (const byte of bytes) {
      for (let bit = 0; bit < 8; bit++) {
        totalBits++;
        if (byte & (1 << bit)) setBits++;
      }
    }
  }
  const ratio = setBits / totalBits;
  return Math.abs(ratio - 0.5) * 2; // 0 = perfect, 1 = fully biased
}

// Profanity GPU wallet generator vulnerability: generated addresses had
// weak entropy in the first few bytes due to GPU seed initialization
function detectProfanityPattern(addresses: string[]): boolean {
  if (addresses.length < 5) return false;
  // Profanity-generated addresses often have specific byte distributions
  // in positions 0-2 due to the truncated GPU seed
  const firstByteFreq = new Map<string, number>();
  for (const addr of addresses) {
    const key = addr.slice(2, 6);
    firstByteFreq.set(key, (firstByteFreq.get(key) ?? 0) + 1);
  }
  const maxFreq = Math.max(...firstByteFreq.values());
  return maxFreq > addresses.length * 0.15; // >15% share the same first 2 bytes
}

function detectSequential(addresses: string[]): number {
  let count = 0;
  const addrNums = addresses.map(a => BigInt(a));
  addrNums.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  for (let i = 1; i < addrNums.length; i++) {
    const diff = addrNums[i]! - addrNums[i - 1]!;
    if (diff < BigInt(1000)) count++;
  }
  return count;
}

function detectDuplicates(addresses: string[]): number {
  const seen = new Set<string>();
  let dups = 0;
  for (const addr of addresses) {
    if (seen.has(addr)) dups++;
    seen.add(addr);
  }
  return dups;
}

export function auditKeyEntropy(rawAddresses: string[]): KeyEntropyResult {
  const { valid, invalid } = parseAddresses(rawAddresses);
  const findings: EntropyFinding[] = [];

  if (valid.length < 3) {
    return {
      addressCount: rawAddresses.length,
      validAddresses: valid,
      invalidAddresses: invalid,
      findings: [{
        id: "INSUFFICIENT_SAMPLE",
        severity: "low",
        title: "Insufficient sample size",
        detail: "Provide at least 3 valid Ethereum addresses for meaningful entropy analysis. For reliable statistical results, 20+ addresses are recommended.",
        attackVector: "N/A",
        remediation: "Generate a larger sample of addresses from your wallet system and re-run the audit.",
      }],
      stats: {
        byteFrequency: new Array(256).fill(0) as number[],
        chiSquaredStatistic: 0, chiSquaredPValue: "N/A", bitBias: 0,
        avgHammingDistance: 0, minHammingDistance: 0,
        leadingZeroAddresses: 0, sequentialAddresses: 0, duplicateAddresses: 0,
        nullByteHeavyAddresses: 0, profanityPattern: false, knownWeakPatterns: [],
      },
      riskScore: 0,
    };
  }

  // Byte frequency distribution
  const byteFreq = new Array<number>(256).fill(0);
  let totalByteCount = 0;
  for (const addr of valid) {
    const bytes = addressToBytes(addr);
    for (const b of bytes) { byteFreq[b]++; totalByteCount++; }
  }

  // Chi-squared test for uniformity
  const { stat: chiStat, pValue } = chiSquaredTest(byteFreq, totalByteCount);

  // Bit bias
  const bitBias = computeBitBias(valid);

  // Hamming distances
  let totalHamming = 0;
  let minHamming = Infinity;
  let hammingPairCount = 0;
  const samplePairs = Math.min(valid.length - 1, 50);
  for (let i = 0; i < samplePairs; i++) {
    const d = hammingDistance(valid[i]!, valid[i + 1]!);
    totalHamming += d;
    if (d < minHamming) minHamming = d;
    hammingPairCount++;
  }
  const avgHamming = hammingPairCount > 0 ? totalHamming / hammingPairCount : 0;

  // Leading zero addresses (vanity/Profanity targets)
  const leadingZeroAddresses = valid.filter(a => a.slice(2, 4) === "00").length;

  // Null-byte heavy addresses
  const nullByteHeavyAddresses = valid.filter(a => {
    const bytes = addressToBytes(a);
    return bytes.filter(b => b === 0).length > 4;
  }).length;

  // Sequential addresses
  const sequentialAddresses = detectSequential(valid);

  // Duplicate addresses
  const duplicateAddresses = detectDuplicates(valid);

  // Profanity vulnerability pattern
  const profanityPattern = detectProfanityPattern(valid);

  const knownWeakPatterns: string[] = [];

  // Generate findings based on stats
  if (duplicateAddresses > 0) {
    findings.push({
      id: "DUPLICATE_ADDRESSES",
      severity: "critical",
      title: `${duplicateAddresses} Duplicate Addresses Generated`,
      detail: `Your wallet system generated ${duplicateAddresses} duplicate addresses. This is cryptographically impossible with a secure RNG — it indicates a broken or seeded RNG that cycles through values.`,
      attackVector: "If your RNG cycles, an attacker who knows a few addresses can predict the next ones to be generated and pre-register them, stealing funds meant for new users.",
      remediation: "Replace the RNG implementation with `crypto.getRandomValues()` (browser) or `crypto.randomBytes()` (Node.js). Never use `Math.random()`, seeded PRNGs, or time-based seeds for key generation.",
      evidence: `${duplicateAddresses} duplicate(s) detected in ${valid.length} addresses`,
    });
    knownWeakPatterns.push("Duplicate addresses (broken RNG)");
  }

  if (sequentialAddresses > 0) {
    findings.push({
      id: "SEQUENTIAL_ADDRESSES",
      severity: "critical",
      title: `${sequentialAddresses} Near-Sequential Address Pairs`,
      detail: `${sequentialAddresses} pairs of addresses differ by fewer than 1,000 in their numeric value. Random 20-byte values should almost never be this close — this strongly indicates a counter-based or linearly-incrementing key generator.`,
      attackVector: "An attacker who obtains one address can trivially brute-force the surrounding range (±1000) to discover related wallet addresses, enabling targeted sweeping attacks.",
      remediation: "Ensure each address is generated from a fully independent 256-bit random private key. Do not derive addresses from incrementing counters or sequential seeds.",
      evidence: `${sequentialAddresses} near-sequential pair(s) found`,
    });
    knownWeakPatterns.push("Sequential address generation");
  }

  if (pValue === "p<0.001") {
    findings.push({
      id: "CHI_SQUARED_FAIL",
      severity: "high",
      title: "Byte Distribution Fails Randomness Test (p<0.001)",
      detail: `Chi-squared statistic: ${chiStat.toFixed(2)}. The byte distribution across all addresses is statistically non-uniform at the 99.9% confidence level. A secure RNG should produce addresses with approximately equal frequency for all byte values.`,
      attackVector: "Non-uniform byte distributions indicate a biased RNG. Attackers can use the known bias to dramatically reduce the keyspace they need to brute-force when targeting addresses from your system.",
      remediation: "Audit your private key generation code. Ensure you are using a cryptographically secure random source and correctly sampling the full 256-bit keyspace using secp256k1. Test your RNG with NIST SP 800-22 statistical tests.",
      evidence: `χ²=${chiStat.toFixed(2)}, ${pValue} with 255 degrees of freedom`,
    });
    knownWeakPatterns.push("Non-uniform byte distribution");
  } else if (pValue === "p<0.01") {
    findings.push({
      id: "CHI_SQUARED_WARN",
      severity: "medium",
      title: "Byte Distribution Shows Moderate Non-Uniformity (p<0.01)",
      detail: `Chi-squared statistic: ${chiStat.toFixed(2)}. Moderate deviation from uniform distribution detected. May indicate RNG bias or a small sample size effect.`,
      attackVector: "Mild RNG bias can still reduce effective keyspace — worth investigating before production deployment.",
      remediation: "Test with a larger sample (100+ addresses). If the pattern persists, audit your key generation code.",
      evidence: `χ²=${chiStat.toFixed(2)}, ${pValue}`,
    });
  }

  if (bitBias > 0.05) {
    findings.push({
      id: "BIT_BIAS",
      severity: bitBias > 0.1 ? "high" : "medium",
      title: `Bit-Level Bias Detected: ${(bitBias * 100).toFixed(2)}% deviation from 50/50`,
      detail: `Individual bit values across all addresses deviate ${(bitBias * 100).toFixed(2)}% from the expected 50/50 split. In a perfectly random system, each bit position should be 0 or 1 with equal probability.`,
      attackVector: "Bit-level bias reduces the effective entropy of each key. For example, a 10% bit bias reduces 160-bit address entropy by ~7 bits — cutting the brute-force search space in half four times over.",
      remediation: "Verify your private key generation samples from the full secp256k1 field uniformly. Common mistakes: XOR-folding, truncating to fewer bits, or using platform-specific random sources that have known bias.",
      evidence: `Bit bias: ${(bitBias * 100).toFixed(2)}%`,
    });
    knownWeakPatterns.push(`${(bitBias * 100).toFixed(2)}% bit-level bias`);
  }

  if (minHamming < 20 && valid.length > 5) {
    findings.push({
      id: "LOW_HAMMING",
      severity: minHamming < 10 ? "high" : "medium",
      title: `Suspiciously Similar Key Pair: Minimum Hamming Distance = ${minHamming} bits`,
      detail: `Two addresses differ by only ${minHamming} bits (out of 160 bits). Random 20-byte values should differ by ~80 bits on average. A distance this low indicates the two addresses share the same seed material or generator state.`,
      attackVector: "If an attacker observes one address and knows the RNG is weak, they can perform a targeted partial-brute-force within the small Hamming-distance neighborhood to find related keys.",
      remediation: "Each private key must be generated from a completely independent random source. Check for shared state, reused initialization vectors, or forked processes that share the same RNG seed.",
      evidence: `Minimum Hamming distance: ${minHamming} bits (expected ~80 bits)`,
    });
    knownWeakPatterns.push("Low Hamming distance between pairs");
  }

  if (profanityPattern) {
    findings.push({
      id: "PROFANITY_PATTERN",
      severity: "critical",
      title: "Matches Profanity GPU Wallet Generator Vulnerability Pattern",
      detail: "The first-byte distribution of these addresses matches the statistical signature of the Profanity GPU vanity address generator, which was found to have a critically weak RNG. In 2022, ~160M USD was stolen from Profanity-generated wallets.",
      attackVector: "Profanity used 32-bit GPU seeds instead of 256-bit entropy. Attackers can reconstruct private keys from public addresses alone using reverse-engineering of the GPU seed space (only ~4 billion values to try on a modern GPU — takes minutes).",
      remediation: "If any of these addresses were generated using Profanity or similar GPU-based vanity generators, transfer all funds immediately and regenerate using a hardware wallet or verified CSPRNG. See https://blog.1inch.io/a-vulnerability-disclosed-in-profanity-an-ethereum-vanity-address-tool/",
      evidence: `First-byte clustering pattern matches Profanity vulnerability signature`,
    });
    knownWeakPatterns.push("Profanity GPU wallet vulnerability pattern");
  }

  if (leadingZeroAddresses > valid.length * 0.1) {
    findings.push({
      id: "LEADING_ZERO_BIAS",
      severity: "medium",
      title: `${leadingZeroAddresses} Addresses with Leading Zero Bytes`,
      detail: `${leadingZeroAddresses} out of ${valid.length} addresses start with 0x00. Randomly, only ~0.4% of addresses should have leading zero bytes. This over-representation suggests vanity address generation or a biased generator.`,
      attackVector: "Vanity address generators often use weakened RNG (like Profanity). Even 'safe' vanity generators narrow the keyspace — the more vanity bytes, the more drastically the effective keyspace is reduced.",
      remediation: "Do not use vanity address generators for wallet addresses holding significant funds. Generate addresses using a hardware wallet's secure element.",
      evidence: `${leadingZeroAddresses}/${valid.length} addresses (${((leadingZeroAddresses / valid.length) * 100).toFixed(1)}%) have leading zero bytes`,
    });
  }

  if (nullByteHeavyAddresses > 0) {
    findings.push({
      id: "NULL_BYTE_HEAVY",
      severity: "high",
      title: `${nullByteHeavyAddresses} Addresses with Excessive Null Bytes`,
      detail: `${nullByteHeavyAddresses} address(es) contain more than 4 null bytes (0x00). This pattern almost never occurs in randomly generated keys and strongly indicates a generator defect or a deliberately crafted address.`,
      attackVector: "Addresses with many null bytes may have been generated with a severely truncated keyspace. An attacker can target the null-byte-heavy region of the address space specifically.",
      remediation: "Investigate the source of these addresses. If they were generated by your system, there is a critical RNG bug. These addresses should be considered compromised.",
      evidence: `${nullByteHeavyAddresses} addresses with >4 null bytes`,
    });
    knownWeakPatterns.push("Excessive null bytes in addresses");
  }

  if (findings.length === 0) {
    findings.push({
      id: "ENTROPY_PASS",
      severity: "pass",
      title: "No Statistical Weaknesses Detected",
      detail: `All ${valid.length} addresses passed the entropy audit. Byte distribution, bit balance, Hamming distances, and pattern checks all appear consistent with a cryptographically secure random number generator.`,
      attackVector: "N/A",
      remediation: "Continue regular entropy audits as you scale. Increase sample size to 100+ addresses for higher confidence in the statistical results.",
    });
  }

  const riskScore = Math.min(100, findings
    .filter(f => f.severity !== "pass")
    .reduce((s, f) => s + ({ critical: 35, high: 18, medium: 8, low: 3, pass: 0 } as Record<string, number>)[f.severity]!, 0));

  return {
    addressCount: rawAddresses.length,
    validAddresses: valid,
    invalidAddresses: invalid,
    findings,
    stats: {
      byteFrequency: byteFreq,
      chiSquaredStatistic: chiStat,
      chiSquaredPValue: pValue,
      bitBias,
      avgHammingDistance: avgHamming,
      minHammingDistance: minHamming === Infinity ? 0 : minHamming,
      leadingZeroAddresses,
      sequentialAddresses,
      duplicateAddresses,
      nullByteHeavyAddresses,
      profanityPattern,
      knownWeakPatterns,
    },
    riskScore,
  };
}
