// Copyright © 2026 Alpha Unlimited Technologies LLC. All rights reserved.
import { Router } from "express";
import { requireCommandCenter } from "../../middlewares/requireCommandCenter";

import threatintelRouter from "../threatintel";
import securityauditRouter from "../securityaudit";
import toolRunnerRouter from "../toolrunner";
import alphaRouter from "../alpha";
import httpProbeRouter from "../httpprobe";
import dirFuzzerRouter from "../dirfuzzer";
import subdomainScanRouter from "../subdomainscan";
import intruderRouter from "../intruder";
import ghostTraceRouter from "../ghosttrace";
import attackChainRouter from "../attackchain";
import vpnTrackerRouter from "../vpntracker";
import siemRouter from "../siem";
import osintRouter from "../osint";
import usernameIntelRouter from "../usernameintel";
import canaryRouter from "../canary";
import wafRouter from "../waf";
import wafBypassRouter from "../wafbypass";
import socialAccountRouter from "../social-account";
import sslTlsRouter from "../ssltls";
import jwtAnalyzerRouter from "../jwtanalyzer";
import iacScanRouter from "../iacscan";
import interceptorRouter from "../interceptor";
import apiTesterRouter from "../apitester";
import oastTesterRouter from "../oasttester";
import oastServerRouter from "../oastserver";
import depScannerRouter from "../depscanner";
import tokenSequencerRouter from "../tokensequencer";
import wsTesterRouter from "../wstester";
import sastRouter from "../sast";
import quantumAuditRouter from "../quantum-audit";
import commandGovernanceRouter from "../command-governance";
import dependencyMapRouter from "../dependency-map";
import aiSecurityRouter from "../ai-security";
import sqliScannerRouter from "../sqli-scanner";
import imAutomationRouter from "../imautomation";
import firewallPolicyV2Router from "../firewall-policy-v2";
import driftMonitorRouter from "../drift-monitor";
import governanceRouter from "../governance";
import eventGraphRouter from "../event-graph";
import serviceBusRouter from "../service-bus";
import deviceTrustRouter from "../device-trust";
import firewallCoreRouter from "../firewall-core";

const router = Router();

router.use("/threatintel", requireCommandCenter, threatintelRouter);
router.use("/security-audit", requireCommandCenter, securityauditRouter);
router.use("/tool-runner", requireCommandCenter, toolRunnerRouter);
router.use("/alpha", requireCommandCenter, alphaRouter);
router.use("/http-probe", requireCommandCenter, httpProbeRouter);
router.use("/dir-fuzzer", requireCommandCenter, dirFuzzerRouter);
router.use("/subdomain-scan", requireCommandCenter, subdomainScanRouter);
router.use("/intruder", requireCommandCenter, intruderRouter);
router.use("/ghost-trace", requireCommandCenter, ghostTraceRouter);
router.use("/attack-chain", requireCommandCenter, attackChainRouter);
router.use("/vpn-tracker", requireCommandCenter, vpnTrackerRouter);
router.use("/siem", requireCommandCenter, siemRouter);
router.use("/osint", requireCommandCenter, osintRouter);
router.use("/username-intel", requireCommandCenter, usernameIntelRouter);
router.use("/canary", requireCommandCenter, canaryRouter);
router.use("/waf", requireCommandCenter, wafRouter);
router.use("/waf-bypass", requireCommandCenter, wafBypassRouter);
router.use("/social-account", requireCommandCenter, socialAccountRouter);
router.use("/ssl-tls", requireCommandCenter, sslTlsRouter);
router.use("/jwt-analyzer", requireCommandCenter, jwtAnalyzerRouter);
router.use("/iac-scan", requireCommandCenter, iacScanRouter);
router.use("/interceptor", requireCommandCenter, interceptorRouter);
router.use("/api-tester", requireCommandCenter, apiTesterRouter);
router.use("/oast-tester", requireCommandCenter, oastTesterRouter);
router.use("/oast/cb", oastServerRouter);
router.use("/oast", requireCommandCenter, oastServerRouter);
router.use("/dep-scanner", requireCommandCenter, depScannerRouter);
router.use("/token-seq", requireCommandCenter, tokenSequencerRouter);
router.use("/ws-tester", requireCommandCenter, wsTesterRouter);
router.use("/sast", requireCommandCenter, sastRouter);
router.use("/quantum-audit", requireCommandCenter, quantumAuditRouter);
router.use("/command-governance", requireCommandCenter, commandGovernanceRouter);
router.use("/dependency-map", requireCommandCenter, dependencyMapRouter);
router.use("/ai-security", requireCommandCenter, aiSecurityRouter);
router.use("/sqli-scanner", requireCommandCenter, sqliScannerRouter);
router.use("/im-auto", requireCommandCenter, imAutomationRouter);

router.use("/firewall-v2", requireCommandCenter, firewallPolicyV2Router);
router.use("/drift-monitor", requireCommandCenter, driftMonitorRouter);
router.use("/governance", requireCommandCenter, governanceRouter);
router.use("/events", requireCommandCenter, eventGraphRouter);
router.use("/service-bus", requireCommandCenter, serviceBusRouter);
router.use("/device-trust", requireCommandCenter, deviceTrustRouter);
router.use("/firewall-core", requireCommandCenter, firewallCoreRouter);

export default router;
