#!/usr/bin/env python3
"""
ProxhqVPN Ghost WireGuard Daemon
=================================
Listens on UDP port 51820 (the standard WireGuard port).
Responds to real WireGuard handshake initiations with valid-looking responses.
Logs everything about the scanner — their index, ephemeral key, timing, behavior.
Includes tarpit delays and an HTTP lure server on port 8080.
Does NOT route any traffic. Does NOT allow tunnel establishment.
The real WireGuard VPN runs on a different port configured at deploy time.

Legal: This runs on servers owned by Alpha Unlimited Technologies LLC.
All responses are generated by our own code. We do not attack any scanner.
We deceive people who probe our infrastructure without permission.

Install:
  pip3 install cryptography requests --break-system-packages
  python3 ghost-wireguard.py --port 51820 --real-wg-port 41194 \
    --backend https://proxhqvpn.com --psk YOUR_HONEYPOT_PSK --node-id NODE_ID

Requirements: Python 3.9+, cryptography>=41.0
"""

import socket
import struct
import threading
import time
import json
import os
import sys
import argparse
import logging
import secrets
import hashlib
import hmac
import ipaddress
import random
import uuid
import urllib.parse
from datetime import datetime, timezone
from typing import Optional, Dict, Tuple
from collections import defaultdict
from http.server import HTTPServer, BaseHTTPRequestHandler

try:
    from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
    from cryptography.hazmat.primitives.kdf.hkdf import HKDF
    import requests
except ImportError:
    print("Install deps: pip3 install cryptography requests", file=sys.stderr)
    sys.exit(1)

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [GhostWG] %(levelname)-7s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("ghost-wg")

# ── WireGuard packet type constants ───────────────────────────────────────────
WG_TYPE_HANDSHAKE_INIT     = 1
WG_TYPE_HANDSHAKE_RESPONSE = 2
WG_TYPE_COOKIE_REPLY       = 3
WG_TYPE_DATA               = 4

LABEL_MAC1   = b"mac1----"
LABEL_COOKIE = b"cookie--"

# ── Rate limiting ─────────────────────────────────────────────────────────────
RATE_LIMIT_MAX = 5
RATE_LIMIT_WIN = 60
_rate_buckets: Dict[str, list] = defaultdict(list)
_rate_lock = threading.Lock()

def is_rate_limited(ip: str) -> bool:
    now = time.time()
    with _rate_lock:
        times = _rate_buckets[ip]
        _rate_buckets[ip] = [t for t in times if now - t < RATE_LIMIT_WIN]
        if len(_rate_buckets[ip]) >= RATE_LIMIT_MAX:
            return True
        _rate_buckets[ip].append(now)
        return False

# ── Ghost WireGuard server state ──────────────────────────────────────────────
_ghost_private_key = X25519PrivateKey.generate()
_ghost_public_key_bytes = _ghost_private_key.public_key().public_bytes(
    serialization.Encoding.Raw, serialization.PublicFormat.Raw
)

_interactions: Dict[str, list] = defaultdict(list)

# ── Hash helpers ──────────────────────────────────────────────────────────────
def blake2s(data: bytes, key: Optional[bytes] = None, length: int = 32) -> bytes:
    if key:
        return hashlib.blake2s(data, key=key[:32], digest_size=length).digest()
    return hashlib.blake2s(data, digest_size=length).digest()

def dh(private_key: X25519PrivateKey, public_bytes: bytes) -> bytes:
    pub = X25519PublicKey.from_public_bytes(public_bytes)
    return private_key.exchange(pub)

def chacha20poly1305_encrypt(key: bytes, nonce_int: int, aad: bytes, plaintext: bytes) -> bytes:
    nonce = struct.pack("<Q", nonce_int) + b"\x00" * 4
    return ChaCha20Poly1305(key).encrypt(nonce, plaintext, aad)

# ── Parse WireGuard Handshake Initiation ─────────────────────────────────────
def parse_handshake_init(data: bytes) -> Optional[Dict]:
    if len(data) != 148:
        return None
    if data[0] != WG_TYPE_HANDSHAKE_INIT:
        return None
    return {
        "type":                  data[0],
        "reserved":              data[1:4],
        "sender_index":          struct.unpack("<I", data[4:8])[0],
        "unencrypted_ephemeral": data[8:40],
        "encrypted_static":      data[40:88],
        "encrypted_timestamp":   data[88:116],
        "mac1":                  data[116:132],
        "mac2":                  data[132:148],
    }

# ── Build a convincing Handshake Response ─────────────────────────────────────
def build_handshake_response(init: Dict) -> Tuple[bytes, Dict]:
    our_ephemeral_private = X25519PrivateKey.generate()
    our_ephemeral_public = our_ephemeral_private.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw
    )

    initiator_ephemeral = init["unencrypted_ephemeral"]
    our_sender_index = secrets.randbelow(0xFFFFFFFF)
    receiver_index = init["sender_index"]

    dh_ee = dh(our_ephemeral_private, initiator_ephemeral)

    response_key = blake2s(
        dh_ee + initiator_ephemeral + our_ephemeral_public + _ghost_public_key_bytes,
        key=None, length=32
    )
    encrypted_nothing = chacha20poly1305_encrypt(response_key, 0, b"", b"")[:16]

    mac1_key = blake2s(LABEL_MAC1 + _ghost_public_key_bytes)
    response_body = (
        bytes([WG_TYPE_HANDSHAKE_RESPONSE]) +
        b"\x00\x00\x00" +
        struct.pack("<I", our_sender_index) +
        struct.pack("<I", receiver_index) +
        our_ephemeral_public +
        encrypted_nothing
    )
    mac1 = blake2s(response_body, key=mac1_key[:32])[:16]
    mac2 = b"\x00" * 16

    response = response_body + mac1 + mac2

    session_info = {
        "our_sender_index":    our_sender_index,
        "receiver_index":      receiver_index,
        "our_ephemeral_pub":   our_ephemeral_public.hex(),
        "initiator_ephemeral": initiator_ephemeral.hex(),
        "dh_ee_hash":          hashlib.sha256(dh_ee).hexdigest()[:16],
    }

    return response, session_info

# ── Report probe to ProxhqVPN backend ────────────────────────────────────────
def report_probe(source_ip: str, source_port: int, init: Dict,
                 session_info: Dict, node_id: str, backend_url: str, psk: str,
                 listen_port: int = 51820, delay_ms: int = 0):
    payload = {
        "nodeId":          node_id,
        "sourceIp":        source_ip,
        "sourcePort":      source_port,
        "probeType":       "wireguard_handshake_init",
        "attackerIp":      source_ip,
        "attackType":      "wireguard_probe",
        "senderIndex":     init["sender_index"],
        "ephemeralKey":    init["unencrypted_ephemeral"].hex(),
        "mac1":            init["mac1"].hex(),
        "respondedWith":   "fake_handshake_response_with_tarpit",
        "sessionInfo":     session_info,
        "portProbed":      listen_port,
        "portLabel":       "GHOST_PORT_51820" if listen_port == 51820 else "REAL_WG_PORT_HIDDEN",
        "honeypotType":    "ghost_wireguard",
        "tarpitApplied":   True,
        "tarpitMs":        delay_ms,
        "timestamp":       datetime.now(timezone.utc).isoformat(),
    }
    try:
        requests.post(
            f"{backend_url}/api/daemon-inbound/honeypot-hit",
            json=payload,
            headers={"X-Daemon-PSK": psk},
            timeout=5,
        )
    except Exception as e:
        log.warning(f"Failed to report probe: {e}")

# ── Tarpit: delayed response ──────────────────────────────────────────────────
def delayed_respond(sock, response_bytes, addr, delay_ms, source_ip, source_port,
                    init, session_info, node_id, backend_url, psk, listen_port):
    """Send the fake response after a tarpit delay, then report."""
    time.sleep(delay_ms / 1000.0)
    try:
        sock.sendto(response_bytes, addr)
        log.info(f"Sent fake handshake to {source_ip}:{source_port} after {delay_ms}ms tarpit")
    except Exception as e:
        log.warning(f"Send failed: {e}")
    report_probe(source_ip, source_port, init, session_info, node_id, backend_url, psk,
                 listen_port=listen_port, delay_ms=delay_ms)

# ── HTTP Lure Server ──────────────────────────────────────────────────────────
LURE_PAGES = {
    "/admin": """<!DOCTYPE html>
<html><head><title>VPN Admin Panel</title></head>
<body style="font-family:Arial;background:#1a1a2e;color:#eee;padding:40px">
<img src="{beacon_url}" width="1" height="1" style="display:none" alt="">
<h2>\U0001f512 ProxhqVPN Admin Panel</h2>
<form>
  <p><input type="text" placeholder="Username" style="padding:8px;width:200px"><br><br>
  <input type="password" placeholder="Password" style="padding:8px;width:200px"><br><br>
  <button type="submit" style="padding:8px 20px;background:#007bff;color:white;border:none">
    Login
  </button></p>
</form>
<p style="color:#888;font-size:12px">ProxhqVPN Management Console v2.4.1</p>
</body></html>""",

    "/phpmyadmin": """<!DOCTYPE html>
<html><head><title>phpMyAdmin</title></head>
<body style="font-family:Arial;background:#f5f5f5;padding:40px">
<img src="{beacon_url}" width="1" height="1" style="display:none" alt="">
<h2>phpMyAdmin</h2>
<p>Username: <input type="text" style="border:1px solid #ccc;padding:4px"></p>
<p>Password: <input type="password" style="border:1px solid #ccc;padding:4px"></p>
<button style="background:#4e9af1;color:white;padding:6px 16px;border:none">Go</button>
<p style="color:#888;font-size:11px">phpMyAdmin 5.2.1</p>
</body></html>""",

    "/wp-login.php": """<!DOCTYPE html>
<html><head><title>WordPress Login</title></head>
<body style="background:#f1f1f1;font-family:Arial;padding:40px">
<img src="{beacon_url}" width="1" height="1" style="display:none" alt="">
<div style="max-width:320px;margin:auto;background:white;padding:26px;border-radius:4px">
<h1 style="text-align:center;font-size:20px">WordPress</h1>
<input type="text" placeholder="Username" style="width:100%;padding:8px;margin:8px 0;box-sizing:border-box"><br>
<input type="password" placeholder="Password" style="width:100%;padding:8px;margin:8px 0;box-sizing:border-box"><br>
<button style="width:100%;background:#0073aa;color:white;padding:10px;border:none">Log In</button>
</div></body></html>""",
}

_lure_config: Dict[str, str] = {}

class LureHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path.rstrip("/") or "/"
        client_ip = self.client_address[0]

        beacon_id = str(uuid.uuid4())
        backend_url = _lure_config.get("backend_url", "")
        beacon_url = f"{backend_url}/api/ghost-trap/beacon/{beacon_id}"
        psk = _lure_config.get("psk", "")
        node_id = _lure_config.get("node_id", "unknown")

        page_template = LURE_PAGES.get(path)
        if not page_template:
            page = b""
            time.sleep(random.uniform(1, 3))
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.send_header("Server", "nginx/1.24.0")
            self.send_header("Content-Length", "0")
            self.end_headers()
        else:
            page = page_template.replace("{beacon_url}", beacon_url).encode()
            time.sleep(random.uniform(1, 3))
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.send_header("Server", "nginx/1.24.0")
            self.send_header("X-Powered-By", "PHP/8.1.2")
            self.send_header("Content-Length", str(len(page)))
            self.end_headers()
            self.wfile.write(page)

        log.info(f"HTTP lure served: {path} \u2192 {client_ip} (beacon: {beacon_id[:8]}...)")

        threading.Thread(
            target=lambda: requests.post(
                f"{backend_url}/api/daemon-inbound/honeypot-hit",
                json={
                    "nodeId":       node_id,
                    "sourceIp":     client_ip,
                    "sourcePort":   self.client_address[1],
                    "probeType":    f"http_lure_{path.replace('/', '_').strip('_') or 'root'}",
                    "attackerIp":   client_ip,
                    "attackType":   "http_lure_probe",
                    "honeypotType": "http_lure",
                    "lurePath":     path,
                    "beaconId":     beacon_id,
                    "userAgent":    self.headers.get("User-Agent", "unknown"),
                    "portProbed":   8080,
                    "portLabel":    "HTTP_LURE",
                    "timestamp":    datetime.now(timezone.utc).isoformat(),
                },
                headers={"X-Daemon-PSK": psk},
                timeout=5,
            ),
            daemon=True,
        ).start()

    def do_POST(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length).decode("utf-8", errors="replace")
        client_ip = self.client_address[0]
        backend_url = _lure_config.get("backend_url", "")
        psk = _lure_config.get("psk", "")
        node_id = _lure_config.get("node_id", "unknown")

        log.warning(f"CREDENTIAL HARVEST ATTEMPT from {client_ip}: {body[:200]}")

        threading.Thread(
            target=lambda: requests.post(
                f"{backend_url}/api/daemon-inbound/honeypot-hit",
                json={
                    "nodeId":          node_id,
                    "sourceIp":        client_ip,
                    "sourcePort":      self.client_address[1],
                    "probeType":       "credential_submission_on_lure",
                    "attackerIp":      client_ip,
                    "attackType":      "credential_harvest_attempt",
                    "honeypotType":    "http_lure_credential",
                    "submittedData":   body[:500],
                    "portLabel":       "HTTP_LURE",
                    "timestamp":       datetime.now(timezone.utc).isoformat(),
                },
                headers={
                    "X-Daemon-PSK":  psk,
                    "X-Alert-Level": "critical",
                },
                timeout=5,
            ),
            daemon=True,
        ).start()

        time.sleep(2)
        self.send_response(200)
        self.send_header("Content-Type", "text/html")
        self.end_headers()
        self.wfile.write(b"<p style='color:red'>Invalid username or password.</p>")


def start_http_lure_server(backend_url: str, psk: str, node_id: str, port: int = 8080):
    _lure_config["backend_url"] = backend_url
    _lure_config["psk"] = psk
    _lure_config["node_id"] = node_id

    server = HTTPServer(("0.0.0.0", port), LureHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    log.info(f"HTTP lure server running on port {port} (admin, phpmyadmin, wp-login lures active)")
    return server

# ── Main server loop ──────────────────────────────────────────────────────────
def run_ghost_wireguard(
    listen_port: int,
    real_wg_port: int,
    backend_url: str,
    psk: str,
    node_id: str,
    bind_ip: str = "0.0.0.0",
):
    tarpit_min_ms = int(os.environ.get("GHOST_TARPIT_MIN_MS", "2000"))
    tarpit_max_ms = int(os.environ.get("GHOST_TARPIT_MAX_MS", "8000"))

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind((bind_ip, listen_port))
    sock.settimeout(1.0)

    log.info(f"Ghost WireGuard listening on UDP {bind_ip}:{listen_port}")
    log.info(f"Real WireGuard is on port {real_wg_port} \u2014 completely hidden")
    log.info(f"Ghost public key: {_ghost_public_key_bytes.hex()[:32]}...")
    log.info(f"Tarpit delay: {tarpit_min_ms}\u2013{tarpit_max_ms}ms")

    while True:
        try:
            data, addr = sock.recvfrom(4096)
        except socket.timeout:
            continue
        except Exception as e:
            log.error(f"Socket error: {e}")
            break

        source_ip, source_port = addr[0], addr[1]

        try:
            if ipaddress.ip_address(source_ip).is_private:
                continue
        except ValueError:
            continue

        if is_rate_limited(source_ip):
            log.debug(f"Rate limited: {source_ip}")
            continue

        if len(data) < 4:
            continue

        packet_type = data[0]

        if packet_type == WG_TYPE_HANDSHAKE_INIT and len(data) == 148:
            init = parse_handshake_init(data)
            if not init:
                continue

            log.info(f"WireGuard handshake init from {source_ip}:{source_port} "
                     f"sender_index={init['sender_index']}")

            response, session_info = build_handshake_response(init)

            delay_ms = random.randint(tarpit_min_ms, tarpit_max_ms)
            log.info(f"Tarpitting {source_ip}:{source_port} for {delay_ms}ms before fake response")

            threading.Thread(
                target=delayed_respond,
                args=(sock, response, addr, delay_ms, source_ip, source_port,
                      init, session_info, node_id, backend_url, psk, listen_port),
                daemon=True,
            ).start()

            _interactions[source_ip].append({
                "type": "handshake_init",
                "time": time.time(),
                "sender_index": init["sender_index"],
                "port": source_port,
            })

        elif packet_type == WG_TYPE_DATA:
            log.info(f"Data packet from {source_ip}:{source_port} "
                     f"(scanner believes tunnel is up \u2014 it is not)")
            _interactions[source_ip].append({
                "type": "data_packet_after_fake_handshake",
                "time": time.time(),
                "size": len(data),
            })

            threading.Thread(
                target=report_probe,
                args=(source_ip, source_port,
                      {"sender_index": 0, "unencrypted_ephemeral": b"\x00"*32,
                       "mac1": b"\x00"*16, "mac2": b"\x00"*16},
                      {"type": "data_after_fake_handshake", "size": len(data)},
                      node_id, backend_url, psk),
                kwargs={"listen_port": listen_port},
                daemon=True,
            ).start()

        elif len(data) > 0:
            log.debug(f"Unknown WG packet type {packet_type} from {source_ip}:{source_port}")

# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="ProxhqVPN Ghost WireGuard Daemon")
    parser.add_argument("--port",         type=int, default=51820, help="Ghost port (default: 51820)")
    parser.add_argument("--real-wg-port", type=int, default=41194, help="Real WireGuard port")
    parser.add_argument("--backend",      required=True,           help="ProxhqVPN backend URL")
    parser.add_argument("--psk",          required=True,           help="Daemon PSK for backend auth")
    parser.add_argument("--node-id",      required=True,           help="This node's ID")
    parser.add_argument("--bind",         default="0.0.0.0",       help="Bind IP")
    parser.add_argument("--lure-port",    type=int, default=8080,  help="HTTP lure server port")
    parser.add_argument("--no-lure",      action="store_true",     help="Disable HTTP lure server")
    args = parser.parse_args()

    log.info(f"ProxhqVPN Ghost WireGuard v1.1 \u2014 Node {args.node_id}")
    log.info(f"Deception: port {args.port} (ghost) \u2192 real WG on port {args.real_wg_port}")

    if not args.no_lure:
        start_http_lure_server(
            backend_url=args.backend,
            psk=args.psk,
            node_id=args.node_id,
            port=args.lure_port,
        )

    run_ghost_wireguard(
        listen_port  = args.port,
        real_wg_port = args.real_wg_port,
        backend_url  = args.backend,
        psk          = args.psk,
        node_id      = args.node_id,
        bind_ip      = args.bind,
    )
