uploads = []
generated = []

[[outputs]]
id = "IJDFyPELKQJakMkMUDhlS"
uri = "file://standalone/dist/GhostNet-ALL-PLATFORMS.zip"
type = "unspecified"
title = "GhostNet — ALL PLATFORMS Bundle"

[[outputs]]
id = "DBWveX0PQlMF4FXcZY-xH"
uri = "file://standalone/dist/GhostNet-Windows-x64.zip"
type = "unspecified"
title = "GhostNet — Windows x64"

[[outputs]]
id = "nDf3mC94dpQgogQdEwTlF"
uri = "file://standalone/dist/GhostNet-macOS-arm64.zip"
type = "unspecified"
title = "GhostNet — macOS Apple Silicon (M1/M2/M3/M4)"

[[outputs]]
id = "pn5NOxAaQoyYAB2nN7GGq"
uri = "file://standalone/dist/GhostNet-macOS-x64.zip"
type = "unspecified"
title = "GhostNet — macOS Intel"

[[outputs]]
id = "Cm1szj_yCb26vEMxKd_qI"
uri = "file://standalone/dist/GhostNet-Linux-x64.zip"
type = "unspecified"
title = "GhostNet — Linux x64"

[[outputs]]
id = "7qSkwMHb-7OfuHkkLbe-0"
uri = "file://standalone/dist/GhostNet-Universal-NodeJS.zip"
type = "unspecified"
title = "GhostNet — Universal (Any OS with Node.js)"

[[outputs]]
id = "Or5n7dm_7WNWA6WGMHhth"
uri = "file://standalone/dist/GHOSTNET-INSTALLATION-MANUAL.md"
type = "text"
title = "GhostNet Installation Manual"
