uploads = []

[[generated]]
id = "aIzcr-pWYxfBGVA5N9dWK"
uri = "file://artifacts/ghost-vpn/public/icon.png"
type = "image"
title = "ProxhqVPN ghost shield icon"

[[generated]]
id = "OOJDU__lIWEGhZofJuH0E"
uri = "file://artifacts/ghost-vpn/public/icon-v2.png"
type = "image"
title = "ProxhqVPN hexagon mesh ghost icon"

[[generated]]
id = "R_UTh7e2Hawjrm9K5ia2P"
uri = "file://artifacts/ghost-vpn/public/icon-v3.png"
type = "image"
title = "ProxhqVPN eye lock icon"

[[generated]]
id = "gGC3BTLhzBy1pMOZQ1buJ"
uri = "file://artifacts/ghost-vpn/public/icon-v4.png"
type = "image"
title = "ProxhqVPN shield ghost face icon"

[[outputs]]
id = "IJDFyPELKQJakMkMUDhlS"
uri = "file://standalone/dist/GhostNet-ALL-PLATFORMS.zip"
type = "unspecified"
title = "GhostNet — ALL PLATFORMS Bundle"

[[outputs]]
id = "DBWveX0PQlMF4FXcZY-xH"
uri = "file://standalone/dist/GhostNet-Windows-x64.zip"
type = "unspecified"
title = "GhostNet — Windows x64"

[[outputs]]
id = "nDf3mC94dpQgogQdEwTlF"
uri = "file://standalone/dist/GhostNet-macOS-arm64.zip"
type = "unspecified"
title = "GhostNet — macOS Apple Silicon (M1/M2/M3/M4)"

[[outputs]]
id = "pn5NOxAaQoyYAB2nN7GGq"
uri = "file://standalone/dist/GhostNet-macOS-x64.zip"
type = "unspecified"
title = "GhostNet — macOS Intel"

[[outputs]]
id = "Cm1szj_yCb26vEMxKd_qI"
uri = "file://standalone/dist/GhostNet-Linux-x64.zip"
type = "unspecified"
title = "GhostNet — Linux x64"

[[outputs]]
id = "7qSkwMHb-7OfuHkkLbe-0"
uri = "file://standalone/dist/GhostNet-Universal-NodeJS.zip"
type = "unspecified"
title = "GhostNet — Universal (Any OS with Node.js)"

[[outputs]]
id = "Or5n7dm_7WNWA6WGMHhth"
uri = "file://standalone/dist/GHOSTNET-INSTALLATION-MANUAL.md"
type = "text"
title = "GhostNet Installation Manual"
