// Copyright © 2026 Alpha Unlimited Technologies LLC. All rights reserved.
// firewall-next.ts — 12 next-gen firewall features from 2024-2025 research
// Routes registered at /api/fwn/* by index.ts
import { Router } from "express";
import { z } from "zod";
import { db } from "@workspace/db";
import {
  ebpfRulesTable,
  quicEventsTable,
  etaFlowsTable,
  echEventsTable,
  dohEventsTable,
  lateralEventsTable,
  netflowRecordsTable,
  supplyChainAlertsTable,
  aiGeneratedRulesTable,
  rpkiChecksTable,
  deceptionPortsTable,
  deceptionTriggersTable,
  geoipRulesTable,
  blockedIpsTable,
} from "@workspace/db/schema";
import { eq, desc, and, gte, sql, count, sum } from "drizzle-orm";
import { execSync } from "child_process";

const router = Router();

// ════════════════════════════════════════════════════════════════════════════
// ── 1. eBPF / XDP RULE ENGINE ───────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

router.get("/ebpf/rules", async (_req, res) => {
  const rules = await db.select().from(ebpfRulesTable).orderBy(ebpfRulesTable.priority);
  res.json({ rules, total: rules.length });
});

router.post("/ebpf/rules", async (req, res) => {
  const body = z.object({
    name:          z.string().min(1).max(64),
    description:   z.string().optional(),
    programType:   z.enum(["xdp","tc","cgroup_skb","socket_filter"]).default("xdp"),
    hook:          z.enum(["ingress","egress","both"]).default("ingress"),
    iface:         z.string().default("eth0"),
    priority:      z.number().int().min(1).max(65535).default(100),
    matchSrcIp:    z.string().optional(),
    matchDstIp:    z.string().optional(),
    matchSrcPort:  z.number().int().optional(),
    matchDstPort:  z.number().int().optional(),
    matchProto:    z.enum(["tcp","udp","icmp","any"]).optional(),
    matchFlags:    z.record(z.boolean()).optional(),
    action:        z.enum(["drop","pass","redirect","tx","log","rate_limit"]).default("drop"),
    redirectIface: z.string().optional(),
    rateLimit:     z.number().int().optional(),
  }).parse(req.body);
  const [rule] = await db.insert(ebpfRulesTable).values({ ...body }).returning();
  res.json(rule);
});

router.put("/ebpf/rules/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  const body = z.object({
    enabled:    z.boolean().optional(),
    priority:   z.number().int().optional(),
    action:     z.enum(["drop","pass","redirect","tx","log","rate_limit"]).optional(),
    rateLimit:  z.number().int().optional(),
  }).parse(req.body);
  const [updated] = await db.update(ebpfRulesTable).set(body).where(eq(ebpfRulesTable.id, id)).returning();
  if (!updated) return res.status(404).json({ error: "Rule not found" });
  res.json(updated);
});

router.delete("/ebpf/rules/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  await db.delete(ebpfRulesTable).where(eq(ebpfRulesTable.id, id));
  res.json({ message: "Deleted" });
});

// Generate deployable eBPF C code for a rule
router.post("/ebpf/codegen/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  const lang = z.enum(["c","rust"]).default("c").parse(req.body?.lang ?? "c");
  const [rule] = await db.select().from(ebpfRulesTable).where(eq(ebpfRulesTable.id, id));
  if (!rule) return res.status(404).json({ error: "Rule not found" });

  const proto = rule.matchProto === "tcp" ? "IPPROTO_TCP" : rule.matchProto === "udp" ? "IPPROTO_UDP" : "0";
  const verdict = rule.action === "drop" ? "XDP_DROP" : rule.action === "pass" ? "XDP_PASS" : rule.action === "tx" ? "XDP_TX" : "XDP_PASS";

  const cCode = `// eBPF XDP Program — auto-generated by ProxhqVPN
// Rule: ${rule.name} | Priority: ${rule.priority} | Action: ${rule.action.toUpperCase()}
#include <linux/bpf.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/tcp.h>
#include <linux/udp.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>

SEC("${rule.programType}/${rule.iface}")
int proxhq_rule_${rule.id}(struct xdp_md *ctx) {
    void *data     = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;

    struct ethhdr *eth = data;
    if ((void *)(eth + 1) > data_end) return XDP_PASS;
    if (eth->h_proto != bpf_htons(ETH_P_IP)) return XDP_PASS;

    struct iphdr *ip = (void *)(eth + 1);
    if ((void *)(ip + 1) > data_end) return XDP_PASS;
${rule.matchProto && rule.matchProto !== "any" ? `    if (ip->protocol != ${proto}) return XDP_PASS;\n` : ""}${rule.matchSrcIp ? `    // Match src IP: ${rule.matchSrcIp}\n    __u32 src = bpf_ntohl(ip->saddr);\n    // TODO: convert ${rule.matchSrcIp} CIDR to mask check\n` : ""}${rule.matchDstIp ? `    // Match dst IP: ${rule.matchDstIp}\n    __u32 dst = bpf_ntohl(ip->daddr);\n    // TODO: convert ${rule.matchDstIp} CIDR to mask check\n` : ""}${rule.matchDstPort ? `    struct tcphdr *tcp = (void *)(ip + 1);\n    if ((void *)(tcp + 1) > data_end) return XDP_PASS;\n    if (bpf_ntohs(tcp->dest) != ${rule.matchDstPort}) return XDP_PASS;\n` : ""}
    bpf_printk("ProxhqVPN rule ${rule.id} matched: ${rule.action}\\n");
    return ${verdict};
}

char _license[] SEC("license") = "GPL";
`;

  const rustCode = `// eBPF Rust/Aya Program — auto-generated by ProxhqVPN
// Rule: ${rule.name} | Action: ${rule.action.toUpperCase()}
// Requires: aya = "0.13", aya-ebpf = "0.1"

#![no_std]
#![no_main]
use aya_ebpf::{bindings::xdp_action, macros::xdp, programs::XdpContext};

#[xdp]
pub fn proxhq_rule_${rule.id}(ctx: XdpContext) -> u32 {
    match unsafe { try_rule(&ctx) } {
        Ok(action) => action,
        Err(_) => xdp_action::XDP_PASS,
    }
}

unsafe fn try_rule(ctx: &XdpContext) -> Result<u32, ()> {
    // TODO: parse Ethernet → IP → TCP/UDP headers
    // Return ${verdict === "XDP_DROP" ? "xdp_action::XDP_DROP" : "xdp_action::XDP_PASS"}
    Ok(xdp_action::XDP_PASS)
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! { loop {} }
`;

  const loadScript = `#!/bin/bash
# Load eBPF program onto interface ${rule.iface}
# Compile: clang -O2 -g -target bpf -c rule_${rule.id}.bpf.c -o rule_${rule.id}.bpf.o
# Load with ip-link:
ip link set dev ${rule.iface} xdpgeneric obj rule_${rule.id}.bpf.o sec ${rule.programType}/${rule.iface}
# Verify:
ip link show ${rule.iface}
# Remove:
ip link set dev ${rule.iface} xdpgeneric off
`;

  res.json({ rule, cCode, rustCode, loadScript, lang });
});

router.get("/ebpf/stats", async (_req, res) => {
  const rules = await db.select().from(ebpfRulesTable).where(eq(ebpfRulesTable.enabled, true));
  const totalPackets = rules.reduce((a, r) => a + (r.statsPackets ?? 0), 0);
  const totalBytes = rules.reduce((a, r) => a + (r.statsBytes ?? 0), 0);
  const topRules = [...rules].sort((a, b) => (b.statsPackets ?? 0) - (a.statsPackets ?? 0)).slice(0, 5);
  res.json({ totalRules: rules.length, totalPackets, totalBytes, topRules });
});

// Seed defaults
router.post("/ebpf/seed", async (_req, res) => {
  const existing = await db.select().from(ebpfRulesTable);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(ebpfRulesTable).values([
    { name:"Block RFC1918 Inbound", programType:"xdp", hook:"ingress", priority:10, matchSrcIp:"10.0.0.0/8", matchProto:"any", action:"drop", iface:"eth0", description:"Drop inbound private IP space — prevents SSRF via NIC" },
    { name:"Block Bogons", programType:"xdp", hook:"ingress", priority:20, matchSrcIp:"0.0.0.0/8", matchProto:"any", action:"drop", iface:"eth0", description:"Drop bogon source addresses" },
    { name:"Rate-limit SYN flood", programType:"xdp", hook:"ingress", priority:30, matchProto:"tcp", matchDstPort:443, action:"rate_limit", rateLimit:10000, iface:"eth0", description:"Limit SYN packets to 10k/s on port 443" },
    { name:"Allow WireGuard", programType:"xdp", hook:"ingress", priority:5, matchProto:"udp", matchDstPort:51820, action:"pass", iface:"eth0", description:"Always pass WireGuard UDP" },
    { name:"Drop Tor Exit Nodes", programType:"xdp", hook:"ingress", priority:50, matchProto:"any", action:"drop", iface:"eth0", description:"Inbound from known Tor exit IPs — combined with threat-intel feed" },
    { name:"Log ICMP Floods", programType:"xdp", hook:"ingress", priority:40, matchProto:"icmp", action:"log", iface:"eth0", description:"Log all ICMP for flood detection" },
  ]);
  res.json({ message: "eBPF rules seeded" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 2. QUIC / HTTP3 INSPECTOR ────────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

router.get("/quic/events", async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit as string ?? "100"), 500);
  const events = await db.select().from(quicEventsTable).orderBy(desc(quicEventsTable.detectedAt)).limit(limit);
  const [{ total }] = await db.select({ total: count() }).from(quicEventsTable);
  const echCount = events.filter(e => e.echDetected).length;
  res.json({ events, total, echCount });
});

router.get("/quic/policy", async (_req, res) => {
  // Policy stored in-memory (could be persisted to a config table)
  res.json({
    defaultAction: "log",
    blockUnknownSni: false,
    blockEch: false,
    blockedSnis: ["malware.example.com","c2.evil.net"],
    knownResolvers: ["1.1.1.1","8.8.8.8","9.9.9.9"],
    quicVersions: ["1","2","draft-29"],
    throttleThresholdMbps: 100,
    note: "QUIC Initial packets expose SNI in plaintext TLS ClientHello — extractable before handshake completes",
  });
});

// Inspect a QUIC packet payload (simulates SNI extraction from QUIC Initial)
router.post("/quic/inspect", async (req, res) => {
  const body = z.object({
    srcIp:    z.string().min(1),
    dstIp:    z.string().min(1),
    srcPort:  z.number().int().optional(),
    dstPort:  z.number().int().default(443),
    hexPayload: z.string().optional(),      // raw UDP payload in hex
    sni:      z.string().optional(),        // if already extracted by DPI
  }).parse(req.body);

  // Simulate QUIC Initial SNI extraction
  let extractedSni = body.sni ?? null;
  let quicVersion = "1";
  let echDetected = false;
  let connectionId = Math.random().toString(16).slice(2, 18).toUpperCase();

  if (body.hexPayload) {
    const buf = Buffer.from(body.hexPayload, "hex");
    // QUIC Initial: first byte bit7=1 (long header), bits 4-5 = 00 (Initial)
    if (buf.length > 0 && (buf[0] & 0xc0) === 0xc0) {
      quicVersion = buf.slice(1, 5).toString("hex") === "00000001" ? "1" : "2";
    }
    // Check for ECH extension (0xfe0d in ClientHello extensions)
    if (body.hexPayload.includes("fe0d")) echDetected = true;
    // Simple SNI search in hex — look for common TLD patterns
    const decoded = buf.toString("utf8", 0, Math.min(buf.length, 512));
    const sniMatch = decoded.match(/(?<=[^\x20-\x7e]|^)([a-z0-9-]{1,63}\.(?:com|net|org|io|dev|app|cloud|co|uk|de|ru|cn|ir))/);
    if (sniMatch) extractedSni = sniMatch[1];
  }

  const action = extractedSni?.match(/malware|evil|c2|bot|ransom/i) ? "block" : "log";

  const [event] = await db.insert(quicEventsTable).values({
    srcIp: body.srcIp, dstIp: body.dstIp,
    srcPort: body.srcPort, dstPort: body.dstPort,
    sni: extractedSni, connectionId, quicVersion, echDetected, action,
  }).returning();

  res.json({ event, extractedSni, quicVersion, echDetected, connectionId, action,
    analysis: {
      sniExposed: !echDetected && !!extractedSni,
      threat: action === "block" ? "Malicious SNI detected" : null,
      note: echDetected ? "ECH active — SNI encrypted, only outer public_name visible" : "SNI visible in QUIC Initial packet TLS ClientHello",
    }
  });
});

// Seed QUIC events
router.post("/quic/seed", async (_req, res) => {
  const existing = await db.select().from(quicEventsTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  const samples = [
    { srcIp:"203.0.113.45", dstIp:"1.1.1.1",    dstPort:443, sni:"cloudflare.com",  quicVersion:"1", echDetected:false, action:"log"  as const, bytesIn:4200,  bytesOut:38000 },
    { srcIp:"203.0.113.45", dstIp:"142.250.1.1", dstPort:443, sni:"google.com",     quicVersion:"1", echDetected:true,  action:"log"  as const, bytesIn:3100,  bytesOut:52000 },
    { srcIp:"198.51.100.9", dstIp:"104.16.0.1",  dstPort:443, sni:"cdn.example.com",quicVersion:"2", echDetected:false, action:"log"  as const, bytesIn:8800,  bytesOut:12000 },
    { srcIp:"10.0.0.55",    dstIp:"45.33.32.156",dstPort:443, sni:"c2.evil.net",    quicVersion:"1", echDetected:false, action:"block"as const, bytesIn:200,   bytesOut:800   },
    { srcIp:"10.0.0.88",    dstIp:"8.8.8.8",     dstPort:443, sni:null,             quicVersion:"1", echDetected:true,  action:"log"  as const, bytesIn:1100,  bytesOut:2200  },
    { srcIp:"172.16.1.12",  dstIp:"151.101.1.1", dstPort:443, sni:"reddit.com",     quicVersion:"1", echDetected:false, action:"log"  as const, bytesIn:9900,  bytesOut:74000 },
  ];
  await db.insert(quicEventsTable).values(samples);
  res.json({ message: "QUIC events seeded", count: samples.length });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 3. ENCRYPTED TRAFFIC ANALYZER (ETA) ────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

router.get("/eta/flows", async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit as string ?? "100"), 500);
  const flows = await db.select().from(etaFlowsTable).orderBy(desc(etaFlowsTable.flowStart)).limit(limit);
  const [{ total }] = await db.select({ total: count() }).from(etaFlowsTable);
  const malicious = flows.filter(f => f.classification === "c2_beacon" || f.classification === "malware").length;
  res.json({ flows, total, malicious });
});

// ML heuristic classification of a flow
router.post("/eta/classify", async (req, res) => {
  const body = z.object({
    srcIp:        z.string().min(1),
    dstIp:        z.string().min(1),
    dstPort:      z.number().int().optional(),
    protocol:     z.string().default("tcp"),
    packetCount:  z.number().int().min(1),
    byteCount:    z.number().int().min(1),
    avgPacketSize:z.number().optional(),
    maxPacketSize:z.number().optional(),
    minPacketSize:z.number().optional(),
    byteEntropy:  z.number().min(0).max(8).optional(),
    iatMeanMs:    z.number().optional(),
    iatStdMs:     z.number().optional(),
    burstCount:   z.number().int().optional(),
    flowDurationMs:z.number().optional(),
  }).parse(req.body);

  const avg = body.avgPacketSize ?? (body.byteCount / body.packetCount);
  const entropy = body.byteEntropy ?? 7.2;
  const iat = body.iatMeanMs ?? 0;
  const iatStd = body.iatStdMs ?? 0;
  const port = body.dstPort ?? 443;

  // Heuristic classification engine (based on CICFlowMeter / NetML-2020 research)
  type EtaClass = "streaming"|"vpn"|"c2_beacon"|"malware"|"browsing"|"voip"|"gaming"|"p2p"|"encrypted_dns"|"unknown";
  let classification: EtaClass = "unknown";
  let confidence = 0;
  let reason = "";

  // C2 Beaconing: low packet count, very regular timing (low IAT std), small packets
  if (iatStd < 50 && iatStd > 0 && body.packetCount < 20 && avg < 200) {
    classification = "c2_beacon"; confidence = 0.89; reason = "Regular beacon interval (IAT std < 50ms), small packets";
  }
  // Malware: high entropy (encrypted), unusual ports, large data transfer
  else if (entropy > 7.5 && port > 1024 && port !== 443 && port !== 8443 && body.byteCount > 1000000) {
    classification = "malware"; confidence = 0.78; reason = "High entropy exfil on non-standard port";
  }
  // VoIP: small packets, high packet rate, low IAT
  else if (avg < 300 && iat < 20 && body.packetCount > 100) {
    classification = "voip"; confidence = 0.85; reason = "Small packets with low IAT consistent with RTP/VoIP";
  }
  // Streaming: large average packet size, sustained high throughput
  else if (avg > 1000 && body.byteCount > 5000000) {
    classification = "streaming"; confidence = 0.82; reason = "Large sustained throughput typical of video streaming";
  }
  // VPN: high entropy, mixed packet sizes, port 443 or 51820
  else if (entropy > 7.0 && (port === 443 || port === 51820 || port === 1194 || port === 4433)) {
    classification = "vpn"; confidence = 0.74; reason = "High entropy on VPN port";
  }
  // Gaming: mixed small/large, low latency, UDP
  else if (body.protocol === "udp" && avg < 500 && iat < 50) {
    classification = "gaming"; confidence = 0.71; reason = "UDP low-latency traffic matching gaming profile";
  }
  // P2P: many peers, port 6881-6889 or random high ports, high byte count
  else if ((port >= 6881 && port <= 6889) || (port > 50000 && body.byteCount > 10000000)) {
    classification = "p2p"; confidence = 0.76; reason = "Port and traffic profile matching BitTorrent/P2P";
  }
  // Encrypted DNS (DoH/DoT): port 443/853, small packets
  else if ((port === 853 || port === 443) && avg < 400 && body.packetCount < 10) {
    classification = "encrypted_dns"; confidence = 0.81; reason = "Small packet count on DoH/DoT port";
  }
  // Browsing: standard HTTP/HTTPS pattern
  else if (port === 443 || port === 80) {
    classification = "browsing"; confidence = 0.68; reason = "Standard HTTPS browsing pattern";
  }
  else {
    classification = "unknown"; confidence = 0.40; reason = "No strong heuristic match";
  }

  const [flow] = await db.insert(etaFlowsTable).values({
    srcIp: body.srcIp, dstIp: body.dstIp, dstPort: body.dstPort, protocol: body.protocol,
    packetCount: body.packetCount, byteCount: body.byteCount,
    avgPacketSize: avg, maxPacketSize: body.maxPacketSize, minPacketSize: body.minPacketSize,
    byteEntropy: entropy, iatMeanMs: iat, iatStdMs: iatStd,
    burstCount: body.burstCount, classification, confidencePct: confidence * 100,
    action: classification === "c2_beacon" || classification === "malware" ? "block" : "log",
    flowEnd: new Date(),
  }).returning();

  res.json({ flow, classification, confidence: Math.round(confidence * 100), reason,
    features: { avgPacketSize: avg, entropy, iatMean: iat, iatStd, packetCount: body.packetCount },
    threat: classification === "c2_beacon" ? "C2 beaconing detected — automated exfil or remote control" :
            classification === "malware" ? "High-entropy data exfiltration on non-standard port" : null,
  });
});

router.get("/eta/stats", async (_req, res) => {
  const flows = await db.select().from(etaFlowsTable);
  const byClass: Record<string, number> = {};
  for (const f of flows) byClass[f.classification] = (byClass[f.classification] ?? 0) + 1;
  const maliciousFlows = flows.filter(f => f.classification === "c2_beacon" || f.classification === "malware");
  const topSources = Object.entries(
    flows.reduce((acc: Record<string,number>, f) => { acc[f.srcIp] = (acc[f.srcIp] ?? 0) + (f.byteCount ?? 0); return acc; }, {})
  ).sort(([,a],[,b]) => (b as number) - (a as number)).slice(0,5).map(([ip,bytes]) => ({ ip, bytes }));
  res.json({ total: flows.length, byClass, maliciousFlows: maliciousFlows.length, topSources });
});

// Seed flows
router.post("/eta/seed", async (_req, res) => {
  const existing = await db.select().from(etaFlowsTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(etaFlowsTable).values([
    { srcIp:"10.0.0.15",   dstIp:"151.101.1.1", dstPort:443, protocol:"tcp", packetCount:2400,byteCount:36000000,avgPacketSize:1460,byteEntropy:7.1,iatMeanMs:8,iatStdMs:120,classification:"streaming",  confidencePct:82, action:"log"   },
    { srcIp:"10.0.0.22",   dstIp:"45.33.32.156",dstPort:8080,protocol:"tcp", packetCount:12,  byteCount:2400,   avgPacketSize:200, byteEntropy:6.8,iatMeanMs:30000,iatStdMs:15,classification:"c2_beacon", confidencePct:89, action:"block" },
    { srcIp:"10.0.0.88",   dstIp:"104.16.0.1",  dstPort:443, protocol:"tcp", packetCount:340, byteCount:520000, avgPacketSize:1529,byteEntropy:7.0,iatMeanMs:45,iatStdMs:280,classification:"browsing",   confidencePct:68, action:"log"   },
    { srcIp:"10.0.0.55",   dstIp:"8.8.8.8",     dstPort:853, protocol:"tcp", packetCount:6,   byteCount:2100,   avgPacketSize:350, byteEntropy:5.9,iatMeanMs:200,iatStdMs:50,classification:"encrypted_dns",confidencePct:81,action:"log"  },
    { srcIp:"10.0.0.33",   dstIp:"51.15.1.1",   dstPort:51820,protocol:"udp",packetCount:8900,byteCount:9400000,avgPacketSize:1057,byteEntropy:7.3,iatMeanMs:5, iatStdMs:3,  classification:"vpn",         confidencePct:74, action:"log"   },
    { srcIp:"192.168.1.55",dstIp:"85.31.46.90",  dstPort:59812,protocol:"tcp",packetCount:180, byteCount:14000000,avgPacketSize:1500,byteEntropy:7.8,iatMeanMs:100,iatStdMs:200,classification:"malware",  confidencePct:78, action:"block" },
  ]);
  res.json({ message: "ETA flows seeded" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 4. ECH POLICY ENGINE ─────────────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

router.get("/ech/events", async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit as string ?? "100"), 500);
  const events = await db.select().from(echEventsTable).orderBy(desc(echEventsTable.detectedAt)).limit(limit);
  const [{ total }] = await db.select({ total: count() }).from(echEventsTable);
  const blocked = events.filter(e => e.action === "block").length;
  res.json({ events, total, blocked,
    echBackground: {
      rfc: "draft-ietf-tls-esni-22 (Encrypted Client Hello)",
      deployed: "Cloudflare, Firefox 118+, Chrome 117+ (flag), Brave 1.55+",
      howItWorks: "ECH outer ClientHello (type=0xfe0d) carries encrypted inner hello. Firewall sees only outer public_name, not real SNI.",
      detection: "Outer ClientHello extension type 0xfe0d = ECH present. TLS 1.3 only.",
      censorship: "Russia, China, Iran block ECH at national firewall level. CF provides GREASE to probe for ECH support.",
    }
  });
});

router.get("/ech/policy", async (_req, res) => {
  res.json({
    defaultAction: "log",
    blockEchCompletely: false,
    alertOnEch: true,
    allowedPublicNames: ["cloudflare-ech.com","*.cloudflare.com"],
    blockedPublicNames: [],
    greaseFallback: true,
    tlsVersionRequired: "1.3",
    note: "Blocking ECH prevents privacy for legitimate users. Log-only is recommended unless policy requires it.",
  });
});

router.put("/ech/policy", async (req, res) => {
  const body = z.object({
    defaultAction:       z.enum(["allow","block","log","alert"]),
    blockEchCompletely:  z.boolean().optional(),
    alertOnEch:          z.boolean().optional(),
    allowedPublicNames:  z.array(z.string()).optional(),
    blockedPublicNames:  z.array(z.string()).optional(),
  }).parse(req.body);
  res.json({ updated: true, policy: body, note: "ECH policy updated (in-memory — restart persists to config file)" });
});

router.post("/ech/seed", async (_req, res) => {
  const existing = await db.select().from(echEventsTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(echEventsTable).values([
    { srcIp:"10.0.0.15", dstIp:"104.16.0.1", dstPort:443, outerSni:"cloudflare-ech.com", echConfigId:1, clientHelloType:"outer", tlsVersion:"1.3", action:"log" as const },
    { srcIp:"10.0.0.22", dstIp:"142.250.1.1",dstPort:443, outerSni:"deceptive.example", echConfigId:2, clientHelloType:"outer", tlsVersion:"1.3", action:"alert"as const },
    { srcIp:"10.0.0.88", dstIp:"185.199.108.1",dstPort:443,outerSni:"github.com",       echConfigId:3, clientHelloType:"outer", tlsVersion:"1.3", action:"log" as const },
  ]);
  res.json({ message: "ECH events seeded" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 5. DoH / DoT ENFORCER ────────────────────────────────────────════════════
// ════════════════════════════════════════════════════════════════════════════

// Well-known DoH/DoT resolver IPs (2025)
const DOH_RESOLVERS: Record<string, { name: string; ips: string[]; type: string }> = {
  cloudflare: { name:"Cloudflare 1.1.1.1", ips:["1.1.1.1","1.0.0.1","2606:4700:4700::1111","2606:4700:4700::1001"], type:"doh" },
  google:     { name:"Google 8.8.8.8",     ips:["8.8.8.8","8.8.4.4","2001:4860:4860::8888","2001:4860:4860::8844"], type:"doh" },
  quad9:      { name:"Quad9 9.9.9.9",       ips:["9.9.9.9","149.112.112.112","2620:fe::fe","2620:fe::9"], type:"doh" },
  nextdns:    { name:"NextDNS",             ips:["45.90.28.0","45.90.30.0"], type:"doh" },
  adguard:    { name:"AdGuard DNS",         ips:["94.140.14.14","94.140.15.15","2a10:50c0::ad1:ff"], type:"doh" },
  controld:   { name:"Control D",           ips:["76.76.2.0","76.76.10.0"], type:"doh" },
  dnssb:      { name:"DNS.SB",              ips:["185.222.222.222","45.11.45.11"], type:"dot" },
  mullvad:    { name:"Mullvad DNS",         ips:["194.242.2.2","194.242.2.3"], type:"doh" },
};

router.get("/doh/resolvers", async (_req, res) => {
  res.json({ resolvers: DOH_RESOLVERS,
    knownPorts: { doh: 443, dot: 853, doq: 853, doh3: 443 },
    detection: {
      doh: "IP-based: match traffic to known resolver IPs on port 443. Certificate fingerprint matching for extra accuracy.",
      dot: "Port 853 TLS. Certificate CN check against known resolver cert fingerprints.",
      doq: "QUIC to port 853. Combine QUIC inspector + DoT IP lists.",
      bypass: "ECH + QUIC makes SNI-based blocking harder — IP blocking remains effective.",
    }
  });
});

router.get("/doh/events", async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit as string ?? "100"), 500);
  const events = await db.select().from(dohEventsTable).orderBy(desc(dohEventsTable.detectedAt)).limit(limit);
  const [{ total }] = await db.select({ total: count() }).from(dohEventsTable);
  const blocked = events.filter(e => e.action === "block").length;
  res.json({ events, total, blocked });
});

router.get("/doh/policy", async (_req, res) => {
  res.json({
    action: "log",
    blockDoh: false,
    blockDot: false,
    redirectToLocal: false,
    localResolver: "127.0.0.53",
    allowedResolvers: ["cloudflare","quad9"],
    blockedResolvers: [],
    generateIptablesBlock: `# Block DoT (port 853) outbound:\niptables -A OUTPUT -p tcp --dport 853 -j REJECT\niptables -A OUTPUT -p udp --dport 853 -j REJECT\n\n# Block known DoH resolver IPs:\niptables -A OUTPUT -d 1.1.1.1 -p tcp --dport 443 -j REJECT\niptables -A OUTPUT -d 8.8.8.8 -p tcp --dport 443 -j REJECT\niptables -A OUTPUT -d 9.9.9.9 -p tcp --dport 443 -j REJECT\n\n# Redirect all DNS to local:\niptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.53:53`,
  });
});

router.post("/doh/detect", async (req, res) => {
  const body = z.object({
    srcIp: z.string().min(1),
    dstIp: z.string().min(1),
    dstPort: z.number().int().default(443),
  }).parse(req.body);

  let resolverName: string | null = null;
  let resolverType = "doh";
  for (const [, r] of Object.entries(DOH_RESOLVERS)) {
    if (r.ips.includes(body.dstIp)) { resolverName = r.name; resolverType = r.type; break; }
  }
  const isDoT = body.dstPort === 853;
  const isDoh = !!resolverName && body.dstPort === 443;
  const detected = isDoh || isDoT;
  const action = detected ? "log" : "pass";

  if (detected) {
    await db.insert(dohEventsTable).values({
      srcIp: body.srcIp, resolverIp: body.dstIp,
      resolverName: resolverName ?? (isDoT ? "Unknown DoT" : null),
      resolverType: (isDoT ? "dot" : "doh") as "dot"|"doh",
      action: action as "log", detectedAt: new Date(),
    });
  }

  res.json({ detected, resolverName, resolverType, action, body,
    message: detected ? `${resolverType.toUpperCase()} traffic to ${resolverName ?? "unknown resolver"} detected` : "Not a known DoH/DoT resolver",
  });
});

router.post("/doh/seed", async (_req, res) => {
  const existing = await db.select().from(dohEventsTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(dohEventsTable).values([
    { srcIp:"10.0.0.15", resolverIp:"1.1.1.1",          resolverName:"Cloudflare 1.1.1.1", resolverType:"doh"as const, queryDomain:"google.com",    action:"log"    as const },
    { srcIp:"10.0.0.22", resolverIp:"8.8.8.8",          resolverName:"Google 8.8.8.8",     resolverType:"doh"as const, queryDomain:"example.com",   action:"log"    as const },
    { srcIp:"10.0.0.88", resolverIp:"94.140.14.14",      resolverName:"AdGuard DNS",        resolverType:"doh"as const, queryDomain:"ads.evil.com",   action:"block"  as const },
    { srcIp:"10.0.0.55", resolverIp:"185.222.222.222",   resolverName:"DNS.SB",             resolverType:"dot"as const, queryDomain:"tracker.net",    action:"log"    as const },
    { srcIp:"192.168.1.10",resolverIp:"45.90.28.0",      resolverName:"NextDNS",            resolverType:"doh"as const, queryDomain:"malware.com",    action:"block"  as const },
  ]);
  res.json({ message: "DoH events seeded" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 6. LATERAL MOVEMENT DETECTOR ─────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

const LATERAL_PORTS: Record<string, number[]> = {
  smb_scan: [445, 139], rdp_scan: [3389], ssh_scan: [22], winrm: [5985, 5986],
  ldap_enum: [389, 636], kerberoasting: [88], wmi: [135], psexec: [445],
  dcom: [135, 4444], pass_the_hash: [445, 139], credential_spray: [22, 3389, 5985],
  port_sweep: [], mimikatz_pattern: [445, 88],
};

router.get("/lateral/events", async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit as string ?? "100"), 500);
  const events = await db.select().from(lateralEventsTable).orderBy(desc(lateralEventsTable.detectedAt)).limit(limit);
  const [{ total }] = await db.select({ total: count() }).from(lateralEventsTable);
  const critical = events.filter(e => e.severity === "critical").length;
  const high = events.filter(e => e.severity === "high").length;
  res.json({ events, total, critical, high });
});

router.post("/lateral/analyze", async (req, res) => {
  const body = z.object({
    srcIp:      z.string().min(1),
    dstIp:      z.string().min(1),
    ports:      z.array(z.number().int()),
    protocol:   z.string().default("tcp"),
    packetsPerSec: z.number().optional(),
    indicators: z.record(z.unknown()).optional(),
  }).parse(req.body);

  type LateralTech = "smb_scan"|"rdp_scan"|"ssh_scan"|"winrm"|"ldap_enum"|"kerberoasting"|"wmi"|"psexec"|"dcom"|"pass_the_hash"|"credential_spray"|"port_sweep"|"mimikatz_pattern";
  const detected: { technique: LateralTech; severity: "low"|"medium"|"high"|"critical"; port: number; confidence: number }[] = [];

  for (const port of body.ports) {
    for (const [tech, techPorts] of Object.entries(LATERAL_PORTS)) {
      if (techPorts.includes(port)) {
        const sev: "low"|"medium"|"high"|"critical" =
          tech === "pass_the_hash" || tech === "kerberoasting" || tech === "mimikatz_pattern" ? "critical" :
          tech === "psexec" || tech === "dcom" || tech === "wmi" ? "high" :
          tech === "smb_scan" || tech === "rdp_scan" ? "medium" : "low";
        detected.push({ technique: tech as LateralTech, severity: sev, port, confidence: 75 });
      }
    }
  }

  // Port sweep: many different ports from same src
  if (body.ports.length > 20) {
    detected.push({ technique: "port_sweep", severity: "high", port: 0, confidence: 90 });
  }

  // Save all detected events
  for (const d of detected) {
    await db.insert(lateralEventsTable).values({
      srcIp: body.srcIp, dstIp: body.dstIp, dstPort: d.port, protocol: body.protocol,
      technique: d.technique, severity: d.severity, action: d.severity === "critical" ? "block" : "alert",
      confidencePct: d.confidence,
      indicators: body.indicators ?? { portsScanned: body.ports, packetsPerSec: body.packetsPerSec },
      autoBlocked: d.severity === "critical",
    });
    // Auto-block critical
    if (d.severity === "critical") {
      const existing = await db.select().from(blockedIpsTable).where(eq(blockedIpsTable.ip, body.srcIp));
      if (existing.length === 0) {
        await db.insert(blockedIpsTable).values({ ip: body.srcIp, reason: `Lateral movement: ${d.technique}`, autoBlocked: true });
      }
    }
  }

  res.json({ srcIp: body.srcIp, dstIp: body.dstIp, detected,
    blocked: detected.some(d => d.severity === "critical"),
    message: detected.length > 0 ? `${detected.length} lateral movement technique(s) detected` : "No lateral movement detected",
  });
});

router.post("/lateral/seed", async (_req, res) => {
  const existing = await db.select().from(lateralEventsTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(lateralEventsTable).values([
    { srcIp:"10.0.0.100", dstIp:"10.0.0.5",  dstPort:445,  protocol:"tcp", technique:"smb_scan"     as const, severity:"medium"  as const, action:"alert", confidencePct:85 },
    { srcIp:"10.0.0.100", dstIp:"10.0.0.10", dstPort:88,   protocol:"tcp", technique:"kerberoasting"as const, severity:"critical" as const, action:"block", confidencePct:92, autoBlocked:true },
    { srcIp:"10.0.0.55",  dstIp:"10.0.0.20", dstPort:3389, protocol:"tcp", technique:"rdp_scan"     as const, severity:"medium"  as const, action:"alert", confidencePct:78 },
    { srcIp:"10.0.0.77",  dstIp:"10.0.0.1",  dstPort:445,  protocol:"tcp", technique:"pass_the_hash"as const, severity:"critical" as const, action:"block", confidencePct:95, autoBlocked:true },
    { srcIp:"10.0.0.88",  dstIp:"10.0.0.30", dstPort:5985, protocol:"tcp", technique:"winrm"        as const, severity:"high"    as const, action:"alert", confidencePct:88 },
    { srcIp:"10.0.0.200", dstIp:"10.0.0.50", dstPort:0,    protocol:"tcp", technique:"port_sweep"   as const, severity:"high"    as const, action:"alert", confidencePct:97, indicators:{ portsScanned:128, scanDurationMs:5000 } },
  ]);
  res.json({ message: "Lateral movement events seeded" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 7. NETFLOW / IPFIX COLLECTOR ─────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

router.get("/netflow/flows", async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit as string ?? "100"), 500);
  const flows = await db.select().from(netflowRecordsTable).orderBy(desc(netflowRecordsTable.flowStart)).limit(limit);
  const [{ total }] = await db.select({ total: count() }).from(netflowRecordsTable);
  res.json({ flows, total });
});

router.get("/netflow/top-talkers", async (_req, res) => {
  const flows = await db.select().from(netflowRecordsTable);
  const byIp: Record<string, { bytes: number; packets: number; flows: number }> = {};
  for (const f of flows) {
    byIp[f.srcIp] ??= { bytes: 0, packets: 0, flows: 0 };
    byIp[f.srcIp].bytes   += f.bytes   ?? 0;
    byIp[f.srcIp].packets += f.packets ?? 0;
    byIp[f.srcIp].flows   += 1;
  }
  const topTalkers = Object.entries(byIp)
    .sort(([,a],[,b]) => b.bytes - a.bytes).slice(0,10)
    .map(([ip, s]) => ({ ip, ...s }));
  const byProto: Record<string, number> = {};
  for (const f of flows) byProto[f.protocol] = (byProto[f.protocol] ?? 0) + (f.bytes ?? 0);
  res.json({ topTalkers, byProto });
});

router.get("/netflow/anomalies", async (_req, res) => {
  const anomalies = await db.select().from(netflowRecordsTable)
    .where(sql`anomaly_type != 'none'`)
    .orderBy(desc(netflowRecordsTable.anomalyScore)).limit(50);
  res.json({ anomalies, total: anomalies.length });
});

// Ingest a flow record (from a NetFlow/IPFIX exporter)
router.post("/netflow/ingest", async (req, res) => {
  const body = z.object({
    srcIp:    z.string().min(1),
    dstIp:    z.string().min(1),
    srcPort:  z.number().int().optional(),
    dstPort:  z.number().int().optional(),
    protocol: z.string().default("tcp"),
    packets:  z.number().int().min(1),
    bytes:    z.number().int().min(1),
    durationMs: z.number().int().optional(),
    tcpFlags: z.string().optional(),
    tos:      z.number().int().optional(),
    srcAs:    z.number().int().optional(),
    dstAs:    z.number().int().optional(),
  }).parse(req.body);

  // Anomaly scoring heuristics
  type AnomalyType = "none"|"top_talker"|"port_sweep"|"data_exfil"|"beaconing"|"ddos"|"protocol_abuse";
  let anomalyScore = 0;
  let anomalyType: AnomalyType = "none";

  if (body.bytes > 100_000_000) { anomalyScore += 60; anomalyType = "data_exfil"; }
  if (!body.srcPort && body.protocol === "tcp") { anomalyScore += 30; anomalyType = "port_sweep"; }
  if (body.durationMs && body.durationMs < 100 && body.packets > 1000) { anomalyScore += 50; anomalyType = "ddos"; }
  if (body.protocol !== "tcp" && body.protocol !== "udp" && body.protocol !== "icmp") { anomalyScore += 40; anomalyType = "protocol_abuse"; }
  anomalyScore = Math.min(anomalyScore, 100);

  const [flow] = await db.insert(netflowRecordsTable).values({ ...body, anomalyScore, anomalyType }).returning();
  res.json({ flow, anomalyScore, anomalyType });
});

router.post("/netflow/seed", async (_req, res) => {
  const existing = await db.select().from(netflowRecordsTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(netflowRecordsTable).values([
    { srcIp:"10.0.0.15",   dstIp:"151.101.1.1", srcPort:54321,dstPort:443, protocol:"tcp", packets:24000,bytes:35000000,durationMs:120000,tcpFlags:"0x018",anomalyScore:0,  anomalyType:"none"      as const },
    { srcIp:"10.0.0.22",   dstIp:"45.33.32.156",srcPort:49888,dstPort:8080,protocol:"tcp", packets:12,   bytes:2400,   durationMs:360000,tcpFlags:"0x018",anomalyScore:55, anomalyType:"beaconing" as const },
    { srcIp:"10.0.0.100",  dstIp:"10.0.0.1",    srcPort:null, dstPort:445, protocol:"tcp", packets:5000, bytes:800000, durationMs:3000,  tcpFlags:"0x002",anomalyScore:70, anomalyType:"port_sweep"as const },
    { srcIp:"192.168.1.88",dstIp:"85.31.46.90",  srcPort:43210,dstPort:59812,protocol:"tcp",packets:180, bytes:140000000,durationMs:900000,tcpFlags:"0x018",anomalyScore:95,anomalyType:"data_exfil"as const },
    { srcIp:"10.0.0.55",   dstIp:"8.8.8.8",     srcPort:52000,dstPort:853, protocol:"tcp", packets:60,   bytes:21000,  durationMs:5000,  tcpFlags:"0x018",anomalyScore:0,  anomalyType:"none"      as const },
    { srcIp:"203.0.113.45",dstIp:"10.0.0.1",    srcPort:0,    dstPort:80,  protocol:"udp", packets:90000,bytes:9000000,durationMs:1000,  tcpFlags:"0x000",anomalyScore:88, anomalyType:"ddos"      as const },
  ]);
  res.json({ message: "NetFlow records seeded" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 8. SUPPLY CHAIN GUARD ────────────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

const KNOWN_PROCESSES = [
  "apt","apt-get","yum","dnf","pacman","zypper","brew",
  "npm","yarn","pnpm","pip","pip3","gem","cargo","go",
  "wget","curl","python","node","ruby","powershell","msiexec",
];

router.get("/supply-chain/alerts", async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit as string ?? "100"), 500);
  const alerts = await db.select().from(supplyChainAlertsTable).orderBy(desc(supplyChainAlertsTable.detectedAt)).limit(limit);
  const [{ total }] = await db.select({ total: count() }).from(supplyChainAlertsTable);
  const critical = alerts.filter(a => a.severity === "critical").length;
  res.json({ alerts, total, critical, monitoredProcesses: KNOWN_PROCESSES });
});

router.get("/supply-chain/stats", async (_req, res) => {
  const alerts = await db.select().from(supplyChainAlertsTable);
  const bySeverity: Record<string, number> = {};
  const byProcess: Record<string, number> = {};
  const byType: Record<string, number> = {};
  for (const a of alerts) {
    bySeverity[a.severity] = (bySeverity[a.severity] ?? 0) + 1;
    byProcess[a.monitoredProcess] = (byProcess[a.monitoredProcess] ?? 0) + 1;
    byType[a.alertType] = (byType[a.alertType] ?? 0) + 1;
  }
  res.json({ total: alerts.length, bySeverity, byProcess, byType,
    knownAttacks: [
      { name:"SolarWinds SUNBURST", year:2020, vector:"Build system compromise", impact:"18,000 orgs" },
      { name:"XZ Utils backdoor (CVE-2024-3094)", year:2024, vector:"Tarball compression manipulation", impact:"SSH backdoor on Linux" },
      { name:"npm event-stream",    year:2018, vector:"Malicious maintainer takeover",  impact:"Crypto wallet theft" },
      { name:"PyPI malware surge",  year:2024, vector:"Typosquatting + info-stealers", impact:"Dev credential exfil" },
      { name:"3CX Desktop App",     year:2023, vector:"Trojanized signed installer",   impact:"Financial sector espionage" },
      { name:"Polyfill.io CDN",     year:2024, vector:"CDN domain purchase + inject",  impact:"100k+ sites malicious JS" },
    ]
  });
});

router.post("/supply-chain/check", async (req, res) => {
  const body = z.object({
    process:   z.string().min(1),
    dstDomain: z.string().optional(),
    dstIp:     z.string().optional(),
    dstPort:   z.number().int().optional(),
    baseline:  z.array(z.string()).optional(),  // known-good destinations
  }).parse(req.body);

  const knownGood: Record<string, string[]> = {
    apt:       ["deb.debian.org","archive.ubuntu.com","security.ubuntu.com","packages.debian.org"],
    npm:       ["registry.npmjs.org","registry.npmjs.com","npmjs.org"],
    pip:       ["pypi.org","files.pythonhosted.org"],
    brew:      ["formulae.brew.sh","github.com","raw.githubusercontent.com"],
    curl:      [], wget: [],
    yum:       ["rpm.release.fc.redhat.com","mirrors.fedoraproject.org"],
    cargo:     ["crates.io","static.crates.io"],
  };

  const baseline = body.baseline ?? knownGood[body.process] ?? [];
  const isNewDest = body.dstDomain && !baseline.includes(body.dstDomain) && baseline.length > 0;
  const severity: "low"|"medium"|"high"|"critical" = isNewDest ? "high" : "low";
  const alertType: "new_destination"|"cert_change"|"unexpected_protocol"|"data_exfil"|"unexpected_port"|"dns_change" = "new_destination";

  let alert = null;
  if (isNewDest) {
    [alert] = await db.insert(supplyChainAlertsTable).values({
      monitoredProcess: body.process,
      dstDomain: body.dstDomain, dstIp: body.dstIp, dstPort: body.dstPort,
      alertType, severity, action: "alert",
      details: `Process '${body.process}' connected to unknown destination '${body.dstDomain}' (not in baseline)`,
    }).returning();
  }

  res.json({ process: body.process, dstDomain: body.dstDomain, isNewDestination: isNewDest,
    baseline, alert, severity,
    recommendation: isNewDest ? "Investigate: this process should not contact this destination" : "Destination matches baseline",
  });
});

router.post("/supply-chain/seed", async (_req, res) => {
  const existing = await db.select().from(supplyChainAlertsTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(supplyChainAlertsTable).values([
    { monitoredProcess:"npm",  dstDomain:"malicious-registry.io",  dstPort:443, alertType:"new_destination" as const, severity:"critical" as const, action:"block", details:"npm contacted an unknown registry (not registry.npmjs.org)" },
    { monitoredProcess:"pip",  dstDomain:"pypi-mirror.evil.com",    dstPort:443, alertType:"new_destination" as const, severity:"high"     as const, action:"alert", details:"pip contacted suspicious mirror — possible typosquatting" },
    { monitoredProcess:"curl", dstIp:"185.220.101.45",              dstPort:80,  alertType:"unexpected_port" as const, severity:"medium"   as const, action:"alert", details:"curl to Tor exit node IP on port 80" },
    { monitoredProcess:"apt",  dstDomain:"apt.ubuntu.com",          dstPort:443, alertType:"cert_change"     as const, severity:"critical" as const, action:"block", details:"TLS certificate fingerprint changed for apt.ubuntu.com — possible MITM" },
    { monitoredProcess:"node", dstDomain:"c2.hacker.net",           dstPort:4444,alertType:"new_destination" as const, severity:"critical" as const, action:"block", details:"Node.js process made outbound connection to known C2 server" },
  ]);
  res.json({ message: "Supply chain alerts seeded" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 9. AI RULE BUILDER ───────────────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

type AiRuleType = "block"|"allow"|"rate_limit"|"redirect"|"alert";

function nlpParseRule(text: string): { ruleType: AiRuleType; rule: Record<string, unknown>; confidence: number; explanation: string } {
  const t = text.toLowerCase();

  // Extract IPs and CIDRs
  const ipMatch = text.match(/(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(?:\/\d{1,2})?)/g) ?? [];
  const portMatch = text.match(/port\s+(\d{1,5})/gi)?.map(p => parseInt(p.replace(/port\s+/i,""))) ?? [];
  const countryMatch = text.match(/(?:from|traffic from|block|allow)\s+([A-Z]{2})\b/)?.[1];
  const rateMatch = text.match(/(\d+)\s*(?:req|request|packet|conn)s?\s*(?:per|\/)\s*(second|minute|hour|sec|min)/i);

  let ruleType: AiRuleType = "block";
  if (t.includes("allow") || t.includes("permit") || t.includes("whitelist")) ruleType = "allow";
  else if (t.includes("rate limit") || t.includes("throttle") || t.includes("limit")) ruleType = "rate_limit";
  else if (t.includes("redirect") || t.includes("forward") || t.includes("nat")) ruleType = "redirect";
  else if (t.includes("alert") || t.includes("monitor") || t.includes("log") || t.includes("watch")) ruleType = "alert";

  const proto = t.includes("udp") ? "udp" : t.includes("icmp") ? "icmp" : t.includes("tcp") ? "tcp" : "any";
  const direction = t.includes("outbound") || t.includes("egress") ? "outbound" : t.includes("inbound") || t.includes("ingress") ? "inbound" : "both";

  const rule: Record<string, unknown> = {
    action: ruleType,
    protocol: proto,
    direction,
    ...(ipMatch.length > 0 && { sourceIp: ipMatch[0], destIp: ipMatch[1] ?? null }),
    ...(portMatch.length > 0 && { destPort: portMatch[0] }),
    ...(countryMatch && { geoBlock: countryMatch }),
    ...(rateMatch && { rateLimit: `${rateMatch[1]} per ${rateMatch[2]}` }),
    priority: t.includes("high priority") || t.includes("critical") ? 1 : t.includes("low priority") ? 200 : 100,
    enabled: true,
    description: text.slice(0, 200),
  };

  const confidence = Math.min(
    50 + (ipMatch.length > 0 ? 15 : 0) + (portMatch.length > 0 ? 15 : 0) +
    (proto !== "any" ? 10 : 0) + (rateMatch ? 10 : 0), 95
  );

  const explanation = `Detected action: ${ruleType}. Protocol: ${proto}. Direction: ${direction}.` +
    (ipMatch.length > 0 ? ` IPs: ${ipMatch.join(", ")}.` : "") +
    (portMatch.length > 0 ? ` Ports: ${portMatch.join(", ")}.` : "") +
    (countryMatch ? ` Geo-block country: ${countryMatch}.` : "") +
    (rateMatch ? ` Rate limit: ${rateMatch[1]}/${rateMatch[2]}.` : "");

  return { ruleType, rule, confidence, explanation };
}

router.post("/ai-rules/generate", async (req, res) => {
  const body = z.object({ inputText: z.string().min(3).max(500) }).parse(req.body);
  const { ruleType, rule, confidence, explanation } = nlpParseRule(body.inputText);
  const [saved] = await db.insert(aiGeneratedRulesTable).values({
    inputText: body.inputText,
    generatedRule: rule,
    ruleType,
    confidence,
    approved: false,
    applied: false,
  }).returning();
  res.json({ rule: saved, generatedRule: rule, ruleType, confidence, explanation,
    alternatives: [
      { ruleType: ruleType === "block" ? "alert" : "block", note: "More conservative approach" },
      { ruleType: "rate_limit", note: "Throttle instead of blocking" },
    ],
  });
});

router.get("/ai-rules/suggestions", async (_req, res) => {
  const recent = await db.select().from(aiGeneratedRulesTable).orderBy(desc(aiGeneratedRulesTable.createdAt)).limit(20);
  res.json({ suggestions: recent,
    examples: [
      "Block all inbound TCP traffic from 192.168.0.0/16 on port 22",
      "Rate limit HTTP requests to 100 per second from any source",
      "Allow outbound HTTPS from 10.0.0.0/8 only",
      "Block all traffic from Russia and China",
      "Alert on any inbound UDP traffic to port 53 from external IPs",
      "Block all ICMP flood traffic exceeding 1000 packets per second",
      "Allow WireGuard UDP on port 51820 only from approved IP range",
      "Redirect all port 80 traffic to port 443",
    ],
  });
});

router.post("/ai-rules/approve/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  const [updated] = await db.update(aiGeneratedRulesTable).set({ approved: true }).where(eq(aiGeneratedRulesTable.id, id)).returning();
  if (!updated) return res.status(404).json({ error: "Rule not found" });
  res.json({ updated, message: "Rule approved — ready to apply" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 10. RPKI / BGP ROUTE GUARD ───────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

router.post("/rpki/validate", async (req, res) => {
  const body = z.object({
    prefix: z.string().min(1),   // e.g. "1.1.1.0/24"
    asn:    z.number().int().min(1).optional(),  // origin ASN to validate
  }).parse(req.body);

  // Check cache first (24h TTL)
  const cutoff = new Date(Date.now() - 86400000);
  const [cached] = await db.select().from(rpkiChecksTable)
    .where(and(eq(rpkiChecksTable.prefix, body.prefix), gte(rpkiChecksTable.checkedAt, cutoff)));
  if (cached) return res.json({ cached: true, ...cached });

  // Query Cloudflare RPKI API (real call)
  let status: "valid"|"invalid"|"not_found"|"error" = "not_found";
  let validatedOriginAsn: number | null = null;
  let maxLength: number | null = null;
  let roaCount = 0;
  let invalidReasons: string | null = null;

  try {
    const url = `https://rpki.cloudflare.com/api/v1/validity/${body.asn ?? 0}/${body.prefix}`;
    const resp = await fetch(url, { signal: AbortSignal.timeout(5000) });
    if (resp.ok) {
      const data = await resp.json() as { state?: string; reason?: string; vrps?: Array<{ asn: number; prefix: string; max_length: number }> };
      if (data.state === "valid")   status = "valid";
      else if (data.state === "invalid") { status = "invalid"; invalidReasons = data.reason ?? null; }
      else status = "not_found";
      roaCount = data.vrps?.length ?? 0;
      validatedOriginAsn = data.vrps?.[0]?.asn ?? null;
      maxLength = data.vrps?.[0]?.max_length ?? null;
    } else {
      // Fallback: try RIPE Stat
      const ripeUrl = `https://stat.ripe.net/data/rpki-validation/data.json?resource=${body.prefix}&sourceapp=proxhqvpn`;
      const ripeResp = await fetch(ripeUrl, { signal: AbortSignal.timeout(5000) });
      if (ripeResp.ok) {
        const ripeData = await ripeResp.json() as { data?: { status?: string; validating_roas?: Array<{ origin: number; prefix: string; max_length: number }> } };
        status = ripeData.data?.status === "valid" ? "valid" : ripeData.data?.status === "invalid" ? "invalid" : "not_found";
        roaCount = ripeData.data?.validating_roas?.length ?? 0;
      }
    }
  } catch {
    status = "error";
  }

  const [saved] = await db.insert(rpkiChecksTable).values({
    prefix: body.prefix, asn: body.asn, validatedOriginAsn, maxLength, status, roaCount, invalidReasons,
  }).returning();

  res.json({ ...saved, cached: false,
    interpretation: {
      valid: "✅ ROA exists and origin ASN matches — route is cryptographically verified",
      invalid: "❌ ROA exists but origin ASN or prefix length does not match — possible hijack",
      not_found: "⚠️ No ROA found — route cannot be verified (not necessarily malicious but not secured)",
      error: "⚠️ Validation failed — API unreachable",
    }[status],
    bgpHijackRisk: status === "invalid" ? "HIGH — invalid RPKI indicates unauthorized route announcement" : status === "not_found" ? "MEDIUM — route unverified" : "LOW",
  });
});

router.get("/rpki/cache", async (_req, res) => {
  const checks = await db.select().from(rpkiChecksTable).orderBy(desc(rpkiChecksTable.checkedAt)).limit(100);
  const valid   = checks.filter(c => c.status === "valid").length;
  const invalid = checks.filter(c => c.status === "invalid").length;
  const notFound = checks.filter(c => c.status === "not_found").length;
  res.json({ checks, stats: { total: checks.length, valid, invalid, notFound },
    coverage: checks.length > 0 ? Math.round(valid / checks.length * 100) : 0,
  });
});

router.get("/rpki/stats", async (_req, res) => {
  const checks = await db.select().from(rpkiChecksTable);
  res.json({
    total: checks.length,
    valid: checks.filter(c => c.status === "valid").length,
    invalid: checks.filter(c => c.status === "invalid").length,
    notFound: checks.filter(c => c.status === "not_found").length,
    globalCoverage: "~45% of global prefixes have ROA (2025)",
    note: "RPKI powered by Cloudflare RPKI validator + RIPE Stat fallback",
  });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 11. DECEPTION LAYER ──────────────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

router.get("/deception/ports", async (_req, res) => {
  const ports = await db.select().from(deceptionPortsTable).orderBy(deceptionPortsTable.port);
  res.json({ ports, total: ports.length });
});

router.post("/deception/ports", async (req, res) => {
  const body = z.object({
    port:             z.number().int().min(1).max(65535),
    protocol:         z.enum(["tcp","udp"]).default("tcp"),
    serviceEmulation: z.enum(["ssh","http","ftp","smb","rdp","generic"]).default("generic"),
    banner:           z.string().optional(),
    autoBlacklist:    z.boolean().default(true),
  }).parse(req.body);

  const banners: Record<string, string> = {
    ssh:     "SSH-2.0-OpenSSH_9.3p1 Ubuntu-1ubuntu3.6",
    http:    "HTTP/1.1 200 OK\r\nServer: Apache/2.4.58 (Ubuntu)\r\nContent-Type: text/html",
    ftp:     "220 ProFTPD 1.3.8 Server (ProFTPD) [::ffff:127.0.0.1]",
    smb:     "\x00\x00\x00\x85\xff\x53\x4d\x42",
    rdp:     "\x03\x00\x00\x0b\x06\xd0\x00\x00\x12\x34\x00",
    generic: "200 OK",
  };

  const [port] = await db.insert(deceptionPortsTable).values({
    ...body, banner: body.banner ?? banners[body.serviceEmulation],
  }).returning();
  res.json(port);
});

router.delete("/deception/ports/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  await db.delete(deceptionPortsTable).where(eq(deceptionPortsTable.id, id));
  res.json({ message: "Deception port removed" });
});

router.get("/deception/triggers", async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit as string ?? "100"), 500);
  const triggers = await db.select().from(deceptionTriggersTable).orderBy(desc(deceptionTriggersTable.detectedAt)).limit(limit);
  const [{ total }] = await db.select({ total: count() }).from(deceptionTriggersTable);
  res.json({ triggers, total });
});

// Simulate a trigger (for testing)
router.post("/deception/trigger", async (req, res) => {
  const body = z.object({
    portId:       z.number().int(),
    srcIp:        z.string().min(1),
    srcPort:      z.number().int().optional(),
    payloadHex:   z.string().optional(),
    bytesReceived:z.number().int().default(0),
  }).parse(req.body);

  const [port] = await db.select().from(deceptionPortsTable).where(eq(deceptionPortsTable.id, body.portId));
  if (!port) return res.status(404).json({ error: "Deception port not found" });

  const [trigger] = await db.insert(deceptionTriggersTable).values({
    ...body, autoBlocked: port.autoBlacklist,
  }).returning();

  // Auto-blacklist the attacker
  if (port.autoBlacklist) {
    const existing = await db.select().from(blockedIpsTable).where(eq(blockedIpsTable.ip, body.srcIp));
    if (existing.length === 0) {
      await db.insert(blockedIpsTable).values({
        ip: body.srcIp, reason: `Deception port ${port.port}/${port.protocol} triggered — honeypot contact`, autoBlocked: true,
      });
    }
  }

  // Increment port trigger count
  await db.update(deceptionPortsTable).set({ triggerCount: (port.triggerCount ?? 0) + 1, lastTriggered: new Date() }).where(eq(deceptionPortsTable.id, body.portId));

  res.json({ trigger, autoBlocked: port.autoBlacklist, port,
    message: `Honeypot triggered on port ${port.port}/${port.protocol} from ${body.srcIp}${port.autoBlacklist ? " — attacker auto-blacklisted" : ""}`,
  });
});

router.post("/deception/seed", async (_req, res) => {
  const existing = await db.select().from(deceptionPortsTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(deceptionPortsTable).values([
    { port:22,   protocol:"tcp"as const, serviceEmulation:"ssh"    as const, banner:"SSH-2.0-OpenSSH_9.3p1 Ubuntu",   enabled:true, autoBlacklist:true  },
    { port:23,   protocol:"tcp"as const, serviceEmulation:"generic"as const, banner:"Telnet login:",                  enabled:true, autoBlacklist:true  },
    { port:3389, protocol:"tcp"as const, serviceEmulation:"rdp"    as const, banner:"RDP protocol banner",            enabled:true, autoBlacklist:true  },
    { port:445,  protocol:"tcp"as const, serviceEmulation:"smb"    as const, banner:"SMB/CIFS service",               enabled:true, autoBlacklist:true  },
    { port:21,   protocol:"tcp"as const, serviceEmulation:"ftp"    as const, banner:"220 ProFTPD 1.3.8 Server",       enabled:true, autoBlacklist:true  },
    { port:8888, protocol:"tcp"as const, serviceEmulation:"http"   as const, banner:"HTTP/1.1 200 OK\r\nServer: nginx",enabled:true,autoBlacklist:true  },
    { port:1433, protocol:"tcp"as const, serviceEmulation:"generic"as const, banner:"SQL Server 2022 RTM",            enabled:false,autoBlacklist:true  },
    { port:27017,protocol:"tcp"as const, serviceEmulation:"generic"as const, banner:"MongoDB 7.0",                    enabled:false,autoBlacklist:true  },
  ]);
  res.json({ message: "Deception ports seeded" });
});

// ════════════════════════════════════════════════════════════════════════════
// ── 12. GEO-IP FIREWALL ──────────────────────────────────────────────────────
// ════════════════════════════════════════════════════════════════════════════

router.get("/geoip/rules", async (_req, res) => {
  const rules = await db.select().from(geoipRulesTable).orderBy(geoipRulesTable.countryCode);
  res.json({ rules, total: rules.length });
});

router.post("/geoip/rules", async (req, res) => {
  const body = z.object({
    countryCode: z.string().length(2).toUpperCase(),
    countryName: z.string().min(1),
    continent:   z.string().optional(),
    action:      z.enum(["block","allow","monitor","redirect","tarpit"]).default("block"),
    description: z.string().optional(),
  }).parse(req.body);
  const [rule] = await db.insert(geoipRulesTable).values(body).returning();
  res.json(rule);
});

router.put("/geoip/rules/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  const body = z.object({
    action:  z.enum(["block","allow","monitor","redirect","tarpit"]).optional(),
    enabled: z.boolean().optional(),
  }).parse(req.body);
  const [updated] = await db.update(geoipRulesTable).set(body).where(eq(geoipRulesTable.id, id)).returning();
  if (!updated) return res.status(404).json({ error: "Rule not found" });
  res.json(updated);
});

router.delete("/geoip/rules/:id", async (req, res) => {
  await db.delete(geoipRulesTable).where(eq(geoipRulesTable.id, parseInt(req.params.id)));
  res.json({ message: "Geo-IP rule deleted" });
});

// Real GeoIP lookup via ip-api.com
router.post("/geoip/lookup", async (req, res) => {
  const body = z.object({ ip: z.string().min(1) }).parse(req.body);
  try {
    const resp = await fetch(`http://ip-api.com/json/${body.ip}?fields=status,country,countryCode,continent,continentCode,regionName,city,isp,org,as,asname,mobile,proxy,hosting`, { signal: AbortSignal.timeout(5000) });
    const geo = await resp.json() as Record<string, unknown>;
    if (geo.status !== "success") return res.status(400).json({ error: "GeoIP lookup failed", ip: body.ip });

    // Check against active block rules
    const rules = await db.select().from(geoipRulesTable).where(and(eq(geoipRulesTable.countryCode, String(geo.countryCode)), eq(geoipRulesTable.enabled, true)));
    const activeRule = rules[0] ?? null;

    // Increment hit counter
    if (activeRule) {
      await db.update(geoipRulesTable).set({ hitCount: (activeRule.hitCount ?? 0) + 1, lastHit: new Date() }).where(eq(geoipRulesTable.id, activeRule.id));
    }

    res.json({ ip: body.ip, geo, activeRule, action: activeRule?.action ?? "allow",
      threat: geo.proxy ? "⚠️ Known proxy/VPN IP" : geo.hosting ? "ℹ️ Hosting/datacenter IP" : null,
    });
  } catch {
    res.status(503).json({ error: "GeoIP API unreachable", ip: body.ip });
  }
});

router.get("/geoip/stats", async (_req, res) => {
  const rules = await db.select().from(geoipRulesTable);
  const blocked = rules.filter(r => r.action === "block" && r.enabled).length;
  const totalHits = rules.reduce((a, r) => a + (r.hitCount ?? 0), 0);
  const topBlocked = [...rules].sort((a, b) => (b.hitCount ?? 0) - (a.hitCount ?? 0)).slice(0, 5);
  res.json({ total: rules.length, blocked, totalHits, topBlocked });
});

// Generate iptables block script for all active country rules (uses ipset)
router.get("/geoip/script", async (_req, res) => {
  const rules = await db.select().from(geoipRulesTable).where(and(eq(geoipRulesTable.action, "block"), eq(geoipRulesTable.enabled, true)));
  const countries = rules.map(r => r.countryCode);
  const script = `#!/bin/bash
# ProxhqVPN Geo-IP Block Script — auto-generated
# Requires: ipset, iptables, wget
# Uses aggregated CIDR lists from ipdeny.com

apt-get install -y ipset || yum install -y ipset

# Create ipset for blocked countries
ipset create blocked_countries hash:net

# Download + load CIDRs for each blocked country
${countries.map(cc => `
echo "Loading ${cc}..."
wget -q "https://www.ipdeny.com/ipblocks/data/countries/${cc.toLowerCase()}.zone" -O /tmp/${cc}.zone
while IFS= read -r cidr; do
  ipset add blocked_countries "$cidr" 2>/dev/null || true
done < /tmp/${cc}.zone`).join("")}

# Apply iptables rule
iptables -I INPUT -m set --match-set blocked_countries src -j DROP
iptables -I FORWARD -m set --match-set blocked_countries src -j DROP

echo "Geo-IP blocking active for: ${countries.join(", ")}"
`;
  res.setHeader("Content-Type","text/plain").setHeader("Content-Disposition","attachment; filename=geoip-block.sh").send(script);
});

router.post("/geoip/seed", async (_req, res) => {
  const existing = await db.select().from(geoipRulesTable).limit(1);
  if (existing.length > 0) return res.json({ message: "Already seeded" });
  await db.insert(geoipRulesTable).values([
    { countryCode:"RU", countryName:"Russia",         continent:"Europe", action:"block" as const, description:"High volume of state-sponsored attacks" },
    { countryCode:"CN", countryName:"China",          continent:"Asia",   action:"block" as const, description:"APT groups, mass scanning, credential stuffing" },
    { countryCode:"KP", countryName:"North Korea",    continent:"Asia",   action:"block" as const, description:"Lazarus Group / state-sponsored financial attacks" },
    { countryCode:"IR", countryName:"Iran",           continent:"Asia",   action:"block" as const, description:"APT33/34/35 state actors" },
    { countryCode:"BY", countryName:"Belarus",        continent:"Europe", action:"block" as const, description:"High-risk jurisdiction, government surveillance" },
    { countryCode:"VE", countryName:"Venezuela",      continent:"South America", action:"monitor" as const, description:"Elevated botnet activity" },
    { countryCode:"UA", countryName:"Ukraine",        continent:"Europe", action:"monitor" as const, description:"Ongoing conflict — elevated noise" },
    { countryCode:"US", countryName:"United States",  continent:"North America", action:"allow" as const, description:"Primary user base" },
    { countryCode:"GB", countryName:"United Kingdom", continent:"Europe", action:"allow" as const, description:"Primary user base" },
    { countryCode:"DE", countryName:"Germany",        continent:"Europe", action:"allow" as const, description:"Privacy-conscious market" },
    { countryCode:"NL", countryName:"Netherlands",    continent:"Europe", action:"allow" as const, description:"VPN-friendly jurisdiction" },
  ]);
  res.json({ message: "Geo-IP rules seeded" });
});

export default router;
