// Copyright © 2026 Alpha Unlimited Technologies LLC. All rights reserved.
import type { Capability } from "@workspace/capabilities";

export type ApiRouteCapability = {
  mountPath: string;
  capability: Capability;
  notes?: string;
};

export const apiRouteCapabilities: ApiRouteCapability[] = [
  { mountPath: "/healthz", capability: "public.read" },
  { mountPath: "/my-ip", capability: "public.read" },
  { mountPath: "/updates", capability: "public.read" },
  { mountPath: "/update/check", capability: "public.read" },
  { mountPath: "/anon", capability: "public.read" },
  { mountPath: "/ambassadors", capability: "public.read" },
  { mountPath: "/stripe", capability: "public.read" },
  { mountPath: "/payments/crypto", capability: "public.read" },
  { mountPath: "/notifications", capability: "public.read" },
  { mountPath: "/wallet", capability: "public.read" },
  { mountPath: "/wallet-intel", capability: "public.read" },
  { mountPath: "/warrant-canary", capability: "public.read" },

  { mountPath: "/me", capability: "auth.read" },
  { mountPath: "/config-lifecycle-events", capability: "vpn.read" },

  { mountPath: "/account-security", capability: "vpn.read" },
  { mountPath: "/leaks", capability: "vpn.read" },
  { mountPath: "/threat-protection", capability: "vpn.read" },
  { mountPath: "/proxy-browser", capability: "vpn.read" },
  { mountPath: "/pqc", capability: "vpn.read" },
  { mountPath: "/daita", capability: "vpn.read" },
  { mountPath: "/darkweb", capability: "vpn.read" },
  { mountPath: "/altid", capability: "vpn.read" },
  { mountPath: "/cve", capability: "vpn.read" },
  { mountPath: "/network-monitor", capability: "vpn.read" },
  { mountPath: "/data-broker", capability: "vpn.read" },
  { mountPath: "/security-score", capability: "vpn.read" },
  { mountPath: "/attack-intel", capability: "vpn.read" },

  { mountPath: "/killswitch", capability: "vpn.write" },
  { mountPath: "/split-tunnel", capability: "vpn.write" },
  { mountPath: "/obfuscation", capability: "vpn.write" },
  { mountPath: "/daemon", capability: "vpn.write" },
  { mountPath: "/vpn-coexist", capability: "vpn.write" },
  { mountPath: "/vpngate", capability: "vpn.write" },
  { mountPath: "/devices", capability: "vpn.write" },
  { mountPath: "/dns-shield", capability: "vpn.write" },
  { mountPath: "/smart-dns", capability: "vpn.write" },
  { mountPath: "/router-config", capability: "vpn.write" },
  { mountPath: "/wireguard", capability: "vpn.write" },
  { mountPath: "/iprotator", capability: "vpn.write" },
  { mountPath: "/ghost-trap", capability: "vpn.write" },
  { mountPath: "/fw", capability: "vpn.write" },
  { mountPath: "/dns-sinkhole", capability: "vpn.write" },
  { mountPath: "/gps-spoof", capability: "vpn.write" },
  { mountPath: "/port-forward", capability: "vpn.write" },
  { mountPath: "/dedicated-ip", capability: "vpn.write" },
  { mountPath: "/meshnet", capability: "vpn.write" },
  { mountPath: "/fwn", capability: "vpn.write" },
  { mountPath: "/fwm", capability: "vpn.write" },
  { mountPath: "/ztna", capability: "vpn.write" },
  { mountPath: "/honeypot", capability: "vpn.write" },

  { mountPath: "/threatintel", capability: "command_center.read" },
  { mountPath: "/ghost-trace", capability: "command_center.read" },
  { mountPath: "/vpn-tracker", capability: "command_center.read" },
  { mountPath: "/siem", capability: "command_center.read" },
  { mountPath: "/command-governance", capability: "command_center.read" },
  { mountPath: "/dependency-map", capability: "command_center.read" },
  { mountPath: "/drift-monitor", capability: "command_center.read" },
  { mountPath: "/governance", capability: "command_center.read" },
  { mountPath: "/events", capability: "command_center.read" },
  { mountPath: "/service-bus", capability: "command_center.read" },

  { mountPath: "/security-audit", capability: "command_center.write" },
  { mountPath: "/tool-runner", capability: "command_center.write" },
  { mountPath: "/alpha", capability: "command_center.write" },
  { mountPath: "/http-probe", capability: "command_center.write" },
  { mountPath: "/dir-fuzzer", capability: "command_center.write" },
  { mountPath: "/subdomain-scan", capability: "command_center.write" },
  { mountPath: "/intruder", capability: "command_center.write" },
  { mountPath: "/attack-chain", capability: "command_center.write" },
  { mountPath: "/osint", capability: "command_center.write" },
  { mountPath: "/username-intel", capability: "command_center.write" },
  { mountPath: "/canary", capability: "command_center.write" },
  { mountPath: "/waf", capability: "command_center.write" },
  { mountPath: "/waf-bypass", capability: "command_center.write" },
  { mountPath: "/social-account", capability: "command_center.write" },
  { mountPath: "/ssl-tls", capability: "command_center.write" },
  { mountPath: "/jwt-analyzer", capability: "command_center.write" },
  { mountPath: "/iac-scan", capability: "command_center.write" },
  { mountPath: "/interceptor", capability: "command_center.write" },
  { mountPath: "/api-tester", capability: "command_center.write" },
  { mountPath: "/oast-tester", capability: "command_center.write" },
  { mountPath: "/oast", capability: "command_center.write" },
  { mountPath: "/dep-scanner", capability: "command_center.write" },
  { mountPath: "/token-seq", capability: "command_center.write" },
  { mountPath: "/ws-tester", capability: "command_center.write" },
  { mountPath: "/sqli-scanner", capability: "command_center.write" },
  { mountPath: "/sast", capability: "command_center.write" },
  { mountPath: "/quantum-audit", capability: "command_center.write" },
  { mountPath: "/ai-security", capability: "command_center.write" },
  { mountPath: "/im-auto", capability: "command_center.write" },
  { mountPath: "/firewall-v2", capability: "command_center.write" },
  { mountPath: "/device-trust", capability: "command_center.write" },
  { mountPath: "/firewall-core", capability: "command_center.write" },
  { mountPath: "/security-graph", capability: "command_center.read" },
  { mountPath: "/security-dashboard-v2", capability: "command_center.read" },

  { mountPath: "/beacons", capability: "admin.read" },
  { mountPath: "/silkweb", capability: "admin.read" },
  { mountPath: "/monitor", capability: "admin.read" },
  { mountPath: "/capability-audit", capability: "admin.read" },
  { mountPath: "/audit-chain", capability: "admin.read" },
  { mountPath: "/control-plane", capability: "admin.read" },
  { mountPath: "/policy-simulation", capability: "admin.read" },

  { mountPath: "/nodes", capability: "admin.write" },
  { mountPath: "/firewall", capability: "admin.write" },
  { mountPath: "/deception", capability: "admin.write" },
  { mountPath: "/node-enrollment", capability: "admin.write" },
  { mountPath: "/node-trust", capability: "admin.write" },
  { mountPath: "/admin/users", capability: "admin.write" },
  { mountPath: "/employees", capability: "admin.write" },
  { mountPath: "/setup", capability: "admin.write" },

  { mountPath: "/terminal", capability: "terminal.exec" },
  { mountPath: "/sql", capability: "sql.exec" },

  { mountPath: "/node-cracker", capability: "security_lab.admin" },
  { mountPath: "/dev-audit", capability: "security_lab.admin" },
  { mountPath: "/omega", capability: "omega.admin" },
];

export function getApiRouteCapability(path: string): ApiRouteCapability | undefined {
  return apiRouteCapabilities
    .filter((route) => path === route.mountPath || path.startsWith(`${route.mountPath}/`))
    .sort((a, b) => b.mountPath.length - a.mountPath.length)[0];
}
